export type QuizCategory =
  | 'errands'
  | 'doctor'
  | 'work'
  | 'smalltalk'
  | 'school'
  | 'rent'

export type QuizDifficulty = 'easy' | 'medium' | 'hard'

interface QuizQuestionBase {
  id: string
  category: QuizCategory
  difficulty: QuizDifficulty
  situation: string
  hint: string
  explanation: string
}

// meaning/response/fillBlank all share the same "3 choices, answer is the
// correct choice index" shape. meaning/fillBlank isolate the target English
// phrase in `phrase` (shown as a quoted headline with a listen button);
// response questions embed the phrase inside `situation` itself (e.g. "카드로
// 낼 경우 자연스러운 대답은?") since the question IS "how do you reply", so
// `phrase` is omitted for that type.
export interface StandardQuizQuestion extends QuizQuestionBase {
  type: 'meaning' | 'response' | 'fillBlank'
  phrase?: string
  choices: string[]
  answer: number
}

// tone questions contrast two phrasings of the same idea and ask which one
// reads as the intended nuance (e.g. more annoyed, more sincere).
export interface ToneQuizQuestion extends QuizQuestionBase {
  type: 'tone'
  phraseA: string
  phraseB: string
  answer: 'A' | 'B'
}

export type QuizQuestion = StandardQuizQuestion | ToneQuizQuestion

export const quizQuestions: QuizQuestion[] = [
  {
    id: 'errands_01',
    category: 'errands',
    type: 'meaning',
    difficulty: 'easy',
    situation: '마트 계산대',
    phrase: 'Paper or plastic?',
    choices: ['종이봉투와 비닐봉투 중 뭘로 드릴지', '종이랑 플라스틱 중 뭘 사실지', '영수증을 종이로 드릴지'],
    answer: 0,
    hint: '봉투 종류를 묻는 아주 흔한 질문이에요',
    explanation: '미국 마트에서 계산 마지막에 자주 듣는 말로, 봉투 재질을 고르라는 뜻이에요.',
  },
  {
    id: 'errands_02',
    category: 'errands',
    type: 'meaning',
    difficulty: 'easy',
    situation: '약국 카운터',
    phrase: 'Do you have insurance with us?',
    choices: ['여기서 보험 가입하신 적 있나요?', '여기 보험료 내신 적 있나요?', '보험사에 다니세요?'],
    answer: 0,
    hint: '"insurance with us"는 이 약국 시스템에 보험 정보가 등록돼 있는지를 물어요',
    explanation: '처방약 받을 때 보험 정보가 등록돼 있는지 확인하는 질문이에요.',
  },
  {
    id: 'errands_03',
    category: 'errands',
    type: 'meaning',
    difficulty: 'medium',
    situation: '세탁소 카운터',
    phrase: 'We can rush this if you need it sooner.',
    choices: ['이거 서두르시면 안 돼요', '급하시면 빠르게 처리해드릴 수 있어요', '이건 너무 급하게 만드셨네요'],
    answer: 1,
    hint: '"rush"는 명사로 쓰이면 "급행 처리"라는 뜻이 있어요',
    explanation: '추가 비용을 받고 더 빨리 처리해줄 수 있다는 제안이에요.',
  },
  {
    id: 'errands_04',
    category: 'errands',
    type: 'response',
    difficulty: 'easy',
    situation: '편의점 계산원이 "Cash or card?"라고 물었을 때, 카드로 낼 경우 자연스러운 대답은?',
    choices: ['"Card, please."', '"Yes, I have a card."', '"I want to pay."'],
    answer: 0,
    hint: '어떤 걸로 낼지 짧게 답하면 충분해요',
    explanation: '이런 질문엔 풀 문장 없이 "Card, please"처럼 짧게 답하는 게 자연스러워요.',
  },
  {
    id: 'errands_05',
    category: 'errands',
    type: 'meaning',
    difficulty: 'easy',
    situation: '주유소 직원',
    phrase: 'Fill it up?',
    choices: ['가득 채워드릴까요?', '채우는 걸 도와드릴까요?', '다 채우셨어요?'],
    answer: 0,
    hint: '주유량을 묻는 아주 짧은 표현이에요',
    explanation: '"Fill it up (the tank)"의 줄임말로, 풀로 주유할지 묻는 말이에요.',
  },
  {
    id: 'errands_06',
    category: 'errands',
    type: 'response',
    difficulty: 'easy',
    situation: '우체국 직원이 "Would you like tracking on this?"라고 물었어요. 배송 조회를 원할 때 자연스러운 대답은?',
    choices: ['"Yes, please."', '"Yes, I\'m tracking it."', '"I want to see it."'],
    answer: 0,
    hint: '원하는지 여부만 짧게 답하면 돼요',
    explanation: '옵션을 원하냐고 물을 땐 "Yes, please"로 간단히 답하는 게 자연스러워요.',
  },
  {
    id: 'errands_07',
    category: 'errands',
    type: 'meaning',
    difficulty: 'medium',
    situation: '미용실 예약',
    phrase: 'I can pencil you in for Thursday.',
    choices: ['목요일에 연필로 적어드릴게요', '목요일로 임시 예약해드릴게요', '목요일엔 예약이 꽉 찼어요'],
    answer: 1,
    hint: '"pencil in"은 연필로 쓴다는 뜻에서 나온 관용 표현이에요',
    explanation: '"pencil in"은 나중에 바뀔 수도 있는 임시 예약을 잡아준다는 뜻이에요.',
  },
  {
    id: 'errands_08',
    category: 'errands',
    type: 'fillBlank',
    difficulty: 'easy',
    situation: '카페에서 주문할 때',
    phrase: 'Can I get a latte ___ go?',
    choices: ['to', 'for', 'at'],
    answer: 0,
    hint: '"포장해서 가져가는" 걸 뜻하는 표현이에요',
    explanation: '"to go"는 매장에서 안 먹고 가져간다는 뜻의 고정 표현이에요.',
  },
  {
    id: 'errands_09',
    category: 'errands',
    type: 'meaning',
    difficulty: 'medium',
    situation: '은행 창구',
    phrase: 'That should clear in a couple business days.',
    choices: ['며칠 안에 처리가 완료될 거예요', '며칠 동안 창구가 비어있을 거예요', '며칠 뒤에 다시 오셔야 해요'],
    answer: 0,
    hint: '"clear"는 수표나 입금이 "정상 처리되다"는 뜻으로도 쓰여요',
    explanation: '입금/수표가 며칠 안에 정상적으로 처리(승인)될 거라는 뜻이에요.',
  },
  {
    id: 'errands_10',
    category: 'errands',
    type: 'response',
    difficulty: 'medium',
    situation: '마트 직원이 카트를 정리해달라고 하는 대신 "You\'re all set, just leave the cart wherever."라고 했어요. 가장 적절한 반응은?',
    choices: ['"Oh, are you sure? Thanks!"', '"Okay, I\'ll leave it in the middle of the aisle."', '"No, I\'ll take it back myself."'],
    answer: 0,
    hint: '상대가 편하게 하라고 했을 때 어느 정도로 반응하는 게 자연스러운지 생각해보세요',
    explanation: '"wherever"는 정말 아무 데나가 아니라 카트 정리대 근처처럼 상식적인 곳을 뜻해요. 그냥 가볍게 감사만 표하는 게 자연스러워요.',
  },
  {
    id: 'errands_11',
    category: 'errands',
    type: 'tone',
    difficulty: 'easy',
    situation: '세탁소 직원이 늦게 찾으러 온 것에 대해 두 가지로 말했어요. 어느 쪽이 더 짜증난 느낌일까요?',
    phraseA: 'No problem, we held it for you.',
    phraseB: 'We were wondering when you\'d come get this.',
    answer: 'B',
    hint: '"wondering"이 여기서 순수한 궁금증인지, 돌려 말하는 지적인지 생각해보세요',
    explanation: 'A는 정말 괜찮다는 뉘앙스, B는 "왜 이제 왔냐"는 은근한 지적이 담겨 있어요.',
  },
  {
    id: 'errands_12',
    category: 'errands',
    type: 'meaning',
    difficulty: 'easy',
    situation: '택배 기사',
    phrase: 'Someone needs to sign for this.',
    choices: ['누군가 서명을 해야 받을 수 있어요', '서명이 필요 없어요', '누가 이걸 주문했는지 알아야 해요'],
    answer: 0,
    hint: '"sign for"는 물건을 받으며 서명한다는 뜻이에요',
    explanation: '서명이 필요한 배송이라 수령인이 직접 서명해야 한다는 뜻이에요.',
  },
  {
    id: 'errands_13',
    category: 'errands',
    type: 'meaning',
    difficulty: 'medium',
    situation: '미용실에서 머리를 자른 후',
    phrase: 'How does that length feel?',
    choices: ['이 길이 마음에 드세요?', '머리가 얼마나 자랐는지 느껴지세요?', '이 길이가 얼마나 되는지 아세요?'],
    answer: 0,
    hint: '"feel"은 실제 촉감이 아니라 만족도를 묻는 데도 쓰여요',
    explanation: '자른 머리 길이가 마음에 드는지 확인하는 질문이에요.',
  },
  {
    id: 'errands_14',
    category: 'errands',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '마트 직원에게 물건 위치를 물을 때, 너무 딱딱하지 않게 물어보려면',
    phrase: 'Excuse me, do you know ___ the cereal is?',
    choices: ['where', 'what', 'which'],
    answer: 0,
    hint: '장소를 묻는 간접의문문이에요',
    explanation: '"do you know where ~ is?"는 물건 위치를 정중하게 묻는 자연스러운 구조예요.',
  },
  {
    id: 'errands_15',
    category: 'errands',
    type: 'tone',
    difficulty: 'medium',
    situation: '카페 직원이 주문 실수를 지적받고 두 가지로 답했어요. 어느 쪽이 더 방어적으로(변명하듯) 들릴까요?',
    phraseA: 'Oh no, let me fix that right away.',
    phraseB: 'That\'s what you ordered, though.',
    answer: 'B',
    hint: '누구 잘못인지를 은근히 강조하는 쪽이 어디인지 보세요',
    explanation: 'A는 바로 인정하고 고치는 태도, B는 "당신이 그렇게 주문했잖아요"라며 책임을 상대에게 미루는 뉘앙스예요.',
  },
  {
    id: 'errands_16',
    category: 'errands',
    type: 'response',
    difficulty: 'medium',
    situation: '은행 직원이 "Is there anything else I can help you with?"라고 물었는데 더 볼일이 없어요. 가장 자연스러운 대답은?',
    choices: ['"No, that\'s all, thank you."', '"No, I don\'t need anything."', '"No, I\'m done here."'],
    answer: 0,
    hint: '감사 인사를 포함한 마무리 표현이 가장 자연스러워요',
    explanation: '"That\'s all, thank you"가 대화를 정중하게 마무리하는 표준적인 표현이에요.',
  },
  {
    id: 'errands_17',
    category: 'errands',
    type: 'meaning',
    difficulty: 'medium',
    situation: '주유소 편의점',
    phrase: 'That\'s gonna be it, or did you want anything else?',
    choices: ['이게 다인가요, 아니면 더 필요하신 거 있으세요?', '이게 마지막 남은 거예요', '다른 물건으로 바꾸시겠어요?'],
    answer: 0,
    hint: '"gonna be it"은 "이게 전부인가요"를 캐주얼하게 말한 거예요',
    explanation: '계산 직전, 더 살 게 있는지 마지막으로 확인하는 캐주얼한 표현이에요.',
  },
  {
    id: 'errands_18',
    category: 'errands',
    type: 'tone',
    difficulty: 'medium',
    situation: '미용실 예약을 취소하려는 손님에게 직원이 두 가지로 답했어요. 어느 쪽이 더 아쉬워하는(서운한) 느낌을 줄까요?',
    phraseA: 'No worries, we\'ll see you next time!',
    phraseB: 'Oh... okay, I\'ll cancel that for you.',
    answer: 'B',
    hint: '대답의 길이와 망설임의 표시("Oh...")가 어떤 감정을 나타내는지 보세요',
    explanation: 'A는 정말 쿨하게 넘어가는 느낌, B는 말줄임표와 짧은 반응으로 살짝 아쉬움이 묻어나요.',
  },
  {
    id: 'errands_19',
    category: 'errands',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '세탁소에서 "제가 다시 올게요"라고 자연스럽게 말하려면',
    phrase: 'I\'ll ___ back to pick it up later.',
    choices: ['come', 'go', 'return'],
    answer: 0,
    hint: '화자가 있는 곳(세탁소)으로 다시 오는 걸 표현해야 해요',
    explanation: '자신이 그 장소로 다시 "오는" 거니까 "come back"이 자연스러워요. "go back"은 화자가 아닌 다른 곳으로 돌아간다는 뉘앙스라 여기선 어색해요.',
  },
  {
    id: 'errands_20',
    category: 'errands',
    type: 'meaning',
    difficulty: 'hard',
    situation: '마트 계산원이 계산하다 말고',
    phrase: 'Let me just double-check on this one for you.',
    choices: ['이건 제가 두 번 계산해드릴게요', '이 가격이 맞는지 확인 좀 해볼게요', '이거 두 개 다 계산해드릴게요'],
    answer: 1,
    hint: '"double-check"는 숫자를 두 배로 한다는 뜻이 아니에요',
    explanation: '"double-check"은 "재확인하다"라는 뜻으로, 가격이나 할인 적용이 맞는지 다시 확인하겠다는 말이에요.',
  },
  {
    id: 'errands_21',
    category: 'errands',
    type: 'response',
    difficulty: 'medium',
    situation: '택배 기사가 "This one\'s kind of heavy, want me to bring it inside?"라고 물었어요. 도움을 받고 싶을 때 가장 자연스러운 대답은?',
    choices: ['"Yeah, that\'d be great, thanks!"', '"Yes, please bring it inside for me."', '"Sure, I need help."'],
    answer: 0,
    hint: '캐주얼한 제안엔 캐주얼하게 화답하는 게 자연스러워요',
    explanation: '"that\'d be great"는 제안을 편하게 수락하는 아주 흔한 표현이에요.',
  },
  {
    id: 'errands_22',
    category: 'errands',
    type: 'meaning',
    difficulty: 'hard',
    situation: '은행 직원이 계좌 개설 절차를 설명하며',
    phrase: 'I just need to run this by my manager real quick.',
    choices: ['이걸 매니저한테 빨리 뛰어가서 전달할게요', '이건 매니저한테 잠깐 확인받고 올게요', '매니저가 이걸 빨리 처리해줄 거예요'],
    answer: 1,
    hint: '"run something by someone"은 실제로 뛰어간다는 뜻이 아니에요',
    explanation: '"run by"는 "~에게 확인/의견을 구하다"라는 관용 표현이에요.',
  },
  {
    id: 'errands_23',
    category: 'errands',
    type: 'tone',
    difficulty: 'hard',
    situation: '미용실 손님이 헤어스타일 결과에 대해 두 가지로 말했어요. 어느 쪽이 실제로는 별로 만족 못 한 느낌일까요?',
    phraseA: 'It\'s exactly what I wanted, thank you!',
    phraseB: 'It\'s... different! I\'ll get used to it.',
    answer: 'B',
    hint: '"different"라는 단어와 "익숙해지겠다"는 말이 실제로 뭘 의미하는지 생각해보세요',
    explanation: 'A는 명확한 만족 표현, B는 말줄임표와 "get used to it"이라는 표현으로 사실은 마음에 안 들지만 예의상 돌려 말하는 뉘앙스예요.',
  },
  {
    id: 'errands_24',
    category: 'errands',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '편의점에서 "그건 이미 계산했어요"를 자연스럽게 표현하려면',
    phrase: 'Oh, that\'s already ___ care of.',
    choices: ['taken', 'taking', 'take'],
    answer: 0,
    hint: '"taken care of"는 "이미 처리된"이라는 뜻의 고정 표현이에요',
    explanation: '"take care of"의 수동태 형태로, 이미 처리/계산이 끝났다는 뜻이에요.',
  },
  {
    id: 'errands_25',
    category: 'errands',
    type: 'meaning',
    difficulty: 'hard',
    situation: '마트 직원이 재고를 확인하고',
    phrase: 'We might have some in the back, let me check.',
    choices: ['창고에 좀 있을 수도 있으니 확인해볼게요', '뒤쪽에 좀 있으니 확인해보세요', '뒷일은 제가 확인해볼게요'],
    answer: 0,
    hint: '"in the back"은 매장 뒤편 창고/재고 공간을 가리켜요',
    explanation: '진열대엔 없지만 창고에 재고가 있을 수 있다는 뜻이에요.',
  },
  {
    id: 'errands_26',
    category: 'errands',
    type: 'tone',
    difficulty: 'hard',
    situation: '세탁소 손님이 옷이 손상된 걸 발견하고 항의했을 때, 직원이 두 가지로 답했어요. 어느 쪽이 더 책임을 인정 안 하는 느낌일까요?',
    phraseA: 'I\'m so sorry, let us take care of this for you.',
    phraseB: 'That\'s strange, it didn\'t look like that when we finished it.',
    answer: 'B',
    hint: '누가 먼저 사과하는지, 누가 원인을 딴 데로 돌리는지 보세요',
    explanation: 'A는 즉각적인 사과와 책임 인정, B는 "이상하네요"라며 은근히 손님 쪽 책임 가능성을 암시하는 뉘앙스예요.',
  },
  {
    id: 'errands_27',
    category: 'errands',
    type: 'response',
    difficulty: 'hard',
    situation: '은행 직원이 대출 승인이 늦어질 수 있다고 하며 "I don\'t want to make any promises, but it should be fine."이라고 했어요. 가장 적절한 반응은?',
    choices: ['"Okay, I appreciate you being upfront about it."', '"So it\'s guaranteed to be approved?"', '"Why can\'t you promise that?"'],
    answer: 0,
    hint: '직원이 왜 "promise"라는 단어를 피했는지 이해하는 반응을 찾아보세요',
    explanation: '"I don\'t want to make any promises"는 확실하지 않을 때 미리 책임을 낮추는 표현이에요.',
  },
  {
    id: 'errands_28',
    category: 'errands',
    type: 'fillBlank',
    difficulty: 'hard',
    situation: '마트 계산원에게 쿠폰이 안 될 수도 있다고 조심스럽게 말할 때',
    phrase: 'This coupon might not ___ , but let me try it anyway.',
    choices: ['go through', 'go on', 'go over'],
    answer: 0,
    hint: '결제/할인이 "적용되다, 처리되다"라는 뜻의 표현이에요',
    explanation: '"go through"는 시스템상 처리/승인된다는 뜻으로, 쿠폰이나 결제가 정상 적용될지 얘기할 때 자주 쓰여요.',
  },
  {
    id: 'errands_29',
    category: 'errands',
    type: 'tone',
    difficulty: 'hard',
    situation: '택배 기사가 파손된 상자를 전달하며 두 가지로 말했어요. 어느 쪽이 더 자기 책임이 아니라고 선을 긋는 느낌일까요?',
    phraseA: 'It looked like this when I picked it up from the warehouse.',
    phraseB: 'Sorry about that, I\'ll report it right away.',
    answer: 'A',
    hint: '누가 문제 발생 시점을 명확히 하며 책임 소재를 가리려 하는지 보세요',
    explanation: 'B는 즉각적인 사과와 조치, A는 "이미 이 상태였다"며 자신의 배송 과정에서는 문제가 없었다고 은근히 책임을 회피하는 뉘앙스예요.',
  },
  {
    id: 'errands_30',
    category: 'errands',
    type: 'fillBlank',
    difficulty: 'hard',
    situation: '은행에서 서류를 깜빡하고 안 가져왔을 때, 정중하게 양해를 구하려면',
    phrase: 'I\'m sorry, I must ___ forgotten to bring that.',
    choices: ['have', 'has', 'had'],
    answer: 0,
    hint: '"must have p.p."는 과거에 대한 추측을 나타내는 문법 구조예요',
    explanation: '"must have forgotten"은 "깜빡한 게 틀림없다"는 뜻으로, 자신의 실수를 인정하면서도 부드럽게 표현하는 방식이에요.',
  },
  {
    id: 'errands_31',
    category: 'errands',
    type: 'response',
    difficulty: 'hard',
    situation: '미용실 직원이 예상보다 오래 걸릴 것 같다며 "This might take a bit longer than I said — is that okay?"라고 물었어요. 시간이 있어서 괜찮을 때 가장 자연스러운 대답은?',
    choices: ['"Yeah, no rush at all."', '"Yes, that is okay with me."', '"It\'s fine, I have nowhere to be."'],
    answer: 0,
    hint: '캐주얼한 상황에선 캐주얼한 관용 표현이 자연스러워요',
    explanation: '"no rush at all"은 "전혀 서두를 필요 없다"는 뜻으로 이런 상황에 가장 자연스럽게 쓰이는 표현이에요.',
  },
  {
    id: 'errands_32',
    category: 'errands',
    type: 'meaning',
    difficulty: 'hard',
    situation: '마트에서 계산원이 카드 결제 오류가 나서',
    phrase: 'It\'s not you, the machine\'s just being weird today.',
    choices: ['당신 카드에는 문제가 없고, 기계가 오늘 이상해요', '당신 잘못이 아니라 기계 담당자가 이상해요', '당신이 아니라 다른 손님 카드가 이상해요'],
    answer: 0,
    hint: '"it\'s not you"는 상대방을 안심시키려는 표현이에요',
    explanation: '결제 오류가 났을 때, 손님 잘못이 아니라 기계 문제라고 미리 안심시켜주는 배려 섞인 표현이에요.',
  },
  {
    id: 'doctor_01',
    category: 'doctor',
    type: 'meaning',
    difficulty: 'easy',
    situation: '병원 접수처',
    phrase: 'Have you been here before?',
    choices: ['전에 여기 와보신 적 있으세요?', '전에 아파보신 적 있으세요?', '여기 얼마나 계셨어요?'],
    answer: 0,
    hint: '초진인지 재진인지 확인하는 흔한 질문이에요',
    explanation: '접수 시 이 병원 진료 기록이 있는지 확인하는 질문이에요.',
  },
  {
    id: 'doctor_02',
    category: 'doctor',
    type: 'meaning',
    difficulty: 'easy',
    situation: '약국',
    phrase: 'Take this twice a day with food.',
    choices: ['음식과 함께 하루에 두 번 드세요', '하루 두 끼만 드세요', '음식은 두 번만 드세요'],
    answer: 0,
    hint: '"twice a day"는 복용 횟수를 말해요',
    explanation: '약 복용 방법을 설명하는 표현으로, 하루 2회 식사와 함께 먹으라는 뜻이에요.',
  },
  {
    id: 'doctor_03',
    category: 'doctor',
    type: 'meaning',
    difficulty: 'medium',
    situation: 'DMV(차량국) 창구',
    phrase: 'You\'ll need to take a number and wait for your turn.',
    choices: ['번호표를 뽑고 차례를 기다리셔야 해요', '숫자를 세면서 기다려야 해요', '번호를 외워서 알려주셔야 해요'],
    answer: 0,
    hint: '"take a number"는 대기 시스템에서 쓰는 표현이에요',
    explanation: '대기 번호표를 뽑고 순서를 기다리라는 안내예요.',
  },
  {
    id: 'doctor_04',
    category: 'doctor',
    type: 'response',
    difficulty: 'easy',
    situation: '병원 접수처에서 "Do you have your insurance card with you?"라고 물었어요. 카드를 갖고 있을 때 자연스러운 대답은?',
    choices: ['"Yes, here it is."', '"Yes, I have it with me now."', '"Yes, I am carrying it."'],
    answer: 0,
    hint: '카드를 건네면서 짧게 답하면 충분해요',
    explanation: '"Here it is"는 물건을 건네며 하는 아주 자연스러운 표현이에요.',
  },
  {
    id: 'doctor_05',
    category: 'doctor',
    type: 'meaning',
    difficulty: 'easy',
    situation: '병원 진료실',
    phrase: 'Any allergies we should know about?',
    choices: ['저희가 알아야 할 알레르기가 있으세요?', '알레르기 검사를 받아보신 적 있으세요?', '알레르기가 왜 생겼는지 아세요?'],
    answer: 0,
    hint: '의료진이 진료 전 필수로 묻는 질문이에요',
    explanation: '약물 처방 전 알레르기 여부를 확인하는 표준 질문이에요.',
  },
  {
    id: 'doctor_06',
    category: 'doctor',
    type: 'response',
    difficulty: 'easy',
    situation: '약사가 "Do you have any questions about this medication?"이라고 물었어요. 궁금한 게 없을 때 자연스러운 대답은?',
    choices: ['"No, I think I\'m good."', '"No, I don\'t have questions."', '"No, nothing to ask."'],
    answer: 0,
    hint: '캐주얼하게 괜찮다고 답하는 표현이에요',
    explanation: '"I\'m good"은 "괜찮다, 문제없다"는 뜻의 아주 흔한 캐주얼 표현이에요.',
  },
  {
    id: 'doctor_07',
    category: 'doctor',
    type: 'meaning',
    difficulty: 'medium',
    situation: '병원 접수처',
    phrase: 'The doctor\'s running a little behind today.',
    choices: ['의사 선생님이 오늘 좀 늦게 오세요', '오늘 진료가 예정보다 좀 지연되고 있어요', '의사 선생님이 오늘 몸이 안 좋으세요'],
    answer: 1,
    hint: '"running behind"는 일정이 밀렸다는 뜻이에요',
    explanation: '진료 일정이 예상보다 늦어지고 있다는 뜻이에요.',
  },
  {
    id: 'doctor_08',
    category: 'doctor',
    type: 'fillBlank',
    difficulty: 'easy',
    situation: '병원에서 접수할 때',
    phrase: 'I have an appointment ___ 2 o\'clock.',
    choices: ['at', 'on', 'in'],
    answer: 0,
    hint: '정확한 시각 앞에 쓰는 전치사예요',
    explanation: '구체적인 시각 앞에는 "at"을 써요.',
  },
  {
    id: 'doctor_09',
    category: 'doctor',
    type: 'meaning',
    difficulty: 'medium',
    situation: '이민국(USCIS) 창구',
    phrase: 'This should be processed within 4 to 6 weeks, give or take.',
    choices: ['정확히 4~6주 안에 처리돼요', '대략 4~6주 정도 걸릴 거예요', '4~6주 동안은 처리가 안 돼요'],
    answer: 1,
    hint: '"give or take"는 "대략"이라는 뜻이에요',
    explanation: '"give or take"는 정확한 숫자가 아니라 어느 정도 오차가 있을 수 있다는 뜻이에요.',
  },
  {
    id: 'doctor_10',
    category: 'doctor',
    type: 'response',
    difficulty: 'medium',
    situation: '응급실 간호사가 "It might be a bit of a wait, I\'m sorry about that."라고 했어요. 가장 적절한 반응은?',
    choices: ['"That\'s okay, thanks for letting me know."', '"How long exactly will it be?"', '"That\'s not okay, I need to see someone now."'],
    answer: 0,
    hint: '상대가 미리 사과하며 양해를 구했을 때 어떻게 반응하는 게 자연스러운지 생각해보세요',
    explanation: '미리 사과한 것에 대해 이해한다는 반응을 보이는 게 자연스러워요.',
  },
  {
    id: 'doctor_11',
    category: 'doctor',
    type: 'tone',
    difficulty: 'easy',
    situation: '병원 접수처 직원이 예약 시간에 늦은 손님에게 두 가지로 말했어요. 어느 쪽이 더 짜증난 느낌일까요?',
    phraseA: 'No worries, we can still fit you in.',
    phraseB: 'We were about to give your spot away.',
    answer: 'B',
    hint: '"were about to"가 무슨 상황을 암시하는지 생각해보세요',
    explanation: 'A는 정말 괜찮다는 여유로운 반응, B는 "하마터면 자리를 놓칠 뻔했다"며 은근히 지각을 지적하는 뉘앙스예요.',
  },
  {
    id: 'doctor_12',
    category: 'doctor',
    type: 'meaning',
    difficulty: 'easy',
    situation: '약국',
    phrase: 'This one might make you a little drowsy.',
    choices: ['이 약은 졸릴 수도 있어요', '이 약은 조금 써요', '이 약은 효과가 조금 늦게 나요'],
    answer: 0,
    hint: '"drowsy"는 졸음과 관련된 단어예요',
    explanation: '약의 부작용으로 졸음이 올 수 있다는 안내예요.',
  },
  {
    id: 'doctor_13',
    category: 'doctor',
    type: 'meaning',
    difficulty: 'medium',
    situation: '시청 민원실',
    phrase: 'You might want to double-check with the front desk on that.',
    choices: ['그건 접수처에서 다시 확인해보시는 게 좋을 것 같아요', '그건 접수처에서 두 번 처리해줄 거예요', '접수처에 두 번 방문하셔야 해요'],
    answer: 0,
    hint: '"you might want to"는 완곡하게 권하는 표현이에요',
    explanation: '확실하지 않으니 접수처에서 재확인하라고 부드럽게 권하는 표현이에요.',
  },
  {
    id: 'doctor_14',
    category: 'doctor',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '병원에서 증상을 설명할 때, 너무 단정적이지 않게 말하려면',
    phrase: 'It\'s been bothering me for ___ a week now.',
    choices: ['about', 'on', 'at'],
    answer: 0,
    hint: '대략적인 기간을 말할 때 쓰는 표현이에요',
    explanation: '"about a week"는 정확히는 아니지만 대략 일주일 정도라는 뜻이에요.',
  },
  {
    id: 'doctor_15',
    category: 'doctor',
    type: 'tone',
    difficulty: 'medium',
    situation: '이민국 담당자가 서류 미비에 대해 두 가지로 말했어요. 어느 쪽이 더 엄격하고 융통성 없게 들릴까요?',
    phraseA: 'We\'re missing one document, let\'s see what we can do.',
    phraseB: 'Without this document, we can\'t move forward.',
    answer: 'B',
    hint: '누가 "같이 해결책을 찾자"는 느낌이고, 누가 "규정이라 안 된다"는 느낌인지 보세요',
    explanation: 'A는 문제를 같이 해결하려는 협조적인 태도, B는 규정을 강조하며 단호하게 선을 긋는 뉘앙스예요.',
  },
  {
    id: 'doctor_16',
    category: 'doctor',
    type: 'response',
    difficulty: 'medium',
    situation: '치과에서 "We recommend a follow-up in six months, does that work for you?"라고 물었어요. 괜찮을 때 가장 자연스러운 대답은?',
    choices: ['"Sure, that works."', '"Yes, that is convenient for me."', '"Okay, I will come then."'],
    answer: 0,
    hint: '캐주얼한 확인 질문엔 캐주얼한 짧은 답이 자연스러워요',
    explanation: '"that works"는 일정이 괜찮다는 뜻의 아주 흔한 캐주얼 표현이에요.',
  },
  {
    id: 'doctor_17',
    category: 'doctor',
    type: 'meaning',
    difficulty: 'medium',
    situation: '병원 접수처',
    phrase: 'We\'ll go ahead and get you checked in.',
    choices: ['저희가 먼저 접수 처리해드릴게요', '앞으로 가시면 체크인하실 수 있어요', '접수는 나중에 다시 오셔서 하시면 돼요'],
    answer: 0,
    hint: '"go ahead and"는 지금 바로 진행하겠다는 뜻이에요',
    explanation: '별다른 절차 없이 바로 접수를 진행하겠다는 뜻이에요.',
  },
  {
    id: 'doctor_18',
    category: 'doctor',
    type: 'tone',
    difficulty: 'medium',
    situation: '응급실 접수 직원이 대기 상황에 대해 두 가지로 말했어요. 어느 쪽이 더 진심으로 미안해하는 느낌일까요?',
    phraseA: 'Yeah, it\'s busy today.',
    phraseB: 'I really apologize for the wait — I know it\'s frustrating.',
    answer: 'B',
    hint: '단순 사실 전달과 공감을 담은 사과의 차이를 보세요',
    explanation: 'A는 사실만 짧게 전달하는 건조한 반응, B는 감정을 인정하며 구체적으로 사과하는 진심 어린 반응이에요.',
  },
  {
    id: 'doctor_19',
    category: 'doctor',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '보험사 전화 상담에서 "제 보험이 이걸 보장하는지 궁금해요"를 자연스럽게 표현하려면',
    phrase: 'I was wondering if this is ___ by my insurance.',
    choices: ['covered', 'covering', 'cover'],
    answer: 0,
    hint: '"보장되다"는 수동태로 표현해요',
    explanation: '"covered by insurance"는 "보험으로 보장되는"이라는 뜻의 표준 표현이에요.',
  },
  {
    id: 'doctor_20',
    category: 'doctor',
    type: 'meaning',
    difficulty: 'hard',
    situation: '이민국 인터뷰에서 담당자가',
    phrase: 'I\'m going to have to flag this for further review.',
    choices: ['이건 나중에 다시 볼 수 있게 표시해둘게요', '이건 추가 검토가 필요해서 따로 표시해둬야겠어요', '이건 문제가 있어서 깃발을 꽂아둘게요'],
    answer: 1,
    hint: '"flag"는 여기서 물리적인 깃발이 아니라 "표시하다"는 뜻의 동사예요',
    explanation: '"flag for review"는 서류나 사안을 추가 검토 대상으로 표시한다는 관용 표현이에요.',
  },
  {
    id: 'doctor_21',
    category: 'doctor',
    type: 'response',
    difficulty: 'medium',
    situation: '약사가 "This might interact with anything else you\'re taking, are you on any other medications?"라고 물었어요. 다른 약을 안 먹고 있을 때 자연스러운 대답은?',
    choices: ['"No, just this one."', '"No, I am not taking any other medications."', '"No, nothing else."'],
    answer: 0,
    hint: '캐주얼한 질문엔 캐주얼한 짧은 답이 자연스러워요',
    explanation: '"just this one"이 가장 자연스럽고 흔한 대답 방식이에요.',
  },
  {
    id: 'doctor_22',
    category: 'doctor',
    type: 'meaning',
    difficulty: 'hard',
    situation: '시청 민원실 직원이',
    phrase: 'That\'s above my pay grade, you\'ll want to talk to a supervisor.',
    choices: ['그건 제 월급보다 비싸서 처리 못 해드려요', '그건 제 권한 밖이라 담당자와 얘기하셔야 해요', '그건 상사분이 월급을 더 받으셔서 처리하실 거예요'],
    answer: 1,
    hint: '"pay grade"는 직급/권한 수준을 뜻하는 관용 표현이에요',
    explanation: '"above my pay grade"는 자신의 직급/권한으로는 처리할 수 없다는 뜻의 관용 표현이에요.',
  },
  {
    id: 'doctor_23',
    category: 'doctor',
    type: 'tone',
    difficulty: 'hard',
    situation: '병원 청구서 관련 전화에서 담당자가 두 가지로 말했어요. 어느 쪽이 더 책임을 회피하는 느낌일까요?',
    phraseA: 'Let me look into this and get back to you.',
    phraseB: 'That\'s really more of a billing department issue.',
    answer: 'B',
    hint: '누가 문제를 직접 떠안으려 하고, 누가 다른 곳으로 넘기려 하는지 보세요',
    explanation: 'A는 직접 확인해서 해결하겠다는 태도, B는 "그건 다른 부서 일이다"라며 책임을 다른 곳으로 넘기는 뉘앙스예요.',
  },
  {
    id: 'doctor_24',
    category: 'doctor',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: 'DMV에서 서류가 부족하다는 말을 들었을 때, "다시 챙겨서 올게요"를 자연스럽게 표현하려면',
    phrase: 'I\'ll come back once I have everything ___ order.',
    choices: ['in', 'on', 'at'],
    answer: 0,
    hint: '"정리된 상태로"라는 뜻의 고정 표현이에요',
    explanation: '"in order"는 "정리된, 준비가 된"이라는 뜻의 관용 표현이에요.',
  },
  {
    id: 'doctor_25',
    category: 'doctor',
    type: 'meaning',
    difficulty: 'hard',
    situation: '이민국 창구 직원이',
    phrase: 'I can\'t speak to that, but the officer handling your case can.',
    choices: ['저는 그것에 대해 말할 수 없지만, 담당관이 말해줄 수 있어요', '저는 그것에 대해 말은 못하지만 들을 수는 있어요', '담당관이 그것에 대해 말하지 못하게 되어있어요'],
    answer: 0,
    hint: '"speak to something"은 "그것에 대해 언급/답변하다"라는 뜻이에요',
    explanation: '"can\'t speak to that"은 자신의 권한/지식 밖이라 답할 수 없다는 뜻이지, 말하는 능력이 없다는 뜻이 아니에요.',
  },
  {
    id: 'doctor_26',
    category: 'doctor',
    type: 'tone',
    difficulty: 'hard',
    situation: '보험사 상담원이 청구 거절에 대해 두 가지로 설명했어요. 어느 쪽이 더 사실은 미안해하지 않는 느낌일까요?',
    phraseA: 'I understand this is frustrating, let me see what options you have.',
    phraseB: 'Unfortunately, that\'s just how the policy works.',
    answer: 'B',
    hint: '누가 대안을 찾아주려 하고, 누가 그냥 규정 탓만 하는지 보세요',
    explanation: 'A는 감정에 공감하며 대안을 찾으려는 태도, B는 "정책이 원래 그렇다"며 무심하게 규정 뒤로 숨는 뉘앙스예요.',
  },
  {
    id: 'doctor_27',
    category: 'doctor',
    type: 'response',
    difficulty: 'hard',
    situation: '의사가 검사 결과를 설명하며 "I don\'t want to alarm you, but we should run a few more tests to be safe."라고 했어요. 가장 적절한 반응은?',
    choices: ['"Okay, I appreciate you being cautious."', '"Wait, is something seriously wrong?"', '"Why do we need more tests if nothing\'s wrong?"'],
    answer: 0,
    hint: '의사가 "alarm하고 싶지 않다"고 먼저 말한 의도를 이해하는 반응을 찾아보세요',
    explanation: '의사가 미리 안심시키려 한 의도를 알아채고 침착하게 받아들이는 반응이 자연스러워요.',
  },
  {
    id: 'doctor_28',
    category: 'doctor',
    type: 'fillBlank',
    difficulty: 'hard',
    situation: '시청에서 다음 절차를 물을 때, "그다음엔 뭘 해야 하나요"를 정중하게 표현하려면',
    phrase: 'What would be the next step, if you don\'t ___ me asking?',
    choices: ['mind', 'care', 'matter'],
    answer: 0,
    hint: '"질문해도 괜찮으시다면"이라는 뜻의 정중한 표현이에요',
    explanation: '"if you don\'t mind me asking"은 질문 전에 붙이는 정중한 완곡 표현이에요.',
  },
  {
    id: 'doctor_29',
    category: 'doctor',
    type: 'tone',
    difficulty: 'hard',
    situation: '응급실 의사가 대기 상황에 대해 환자에게 두 가지로 말했어요. 어느 쪽이 더 상황을 가볍게 취급하는 느낌일까요?',
    phraseA: 'I know the wait\'s been long, thank you for your patience.',
    phraseB: 'You\'re not the only one waiting, you know.',
    answer: 'B',
    hint: '누가 상대의 감정을 인정하고, 누가 오히려 되받아치는지 보세요',
    explanation: 'A는 기다림을 인정하고 감사를 표하는 배려, B는 오히려 환자의 불만을 가볍게 넘기며 살짝 방어적으로 받아치는 뉘앙스예요.',
  },
  {
    id: 'doctor_30',
    category: 'doctor',
    type: 'fillBlank',
    difficulty: 'hard',
    situation: '이민국 서류에 실수가 있어서 "제가 실수한 것 같아요"를 조심스럽게 인정하려면',
    phrase: 'I think I might ___ made an error on this form.',
    choices: ['have', 'has', 'had'],
    answer: 0,
    hint: '"must/might have p.p."는 과거 일에 대한 추측이나 조심스러운 인정을 나타내요',
    explanation: '"might have made"는 "실수했을 수도 있다"는 뜻으로, 확신 없이 조심스럽게 인정하는 표현이에요.',
  },
  {
    id: 'doctor_31',
    category: 'doctor',
    type: 'response',
    difficulty: 'hard',
    situation: '보험사 상담원이 청구 처리가 늦어질 수 있다며 "I can\'t make any guarantees, but I\'ll do what I can on my end."라고 했어요. 가장 적절한 반응은?',
    choices: ['"I really appreciate you trying."', '"So you\'re saying it\'ll definitely work out?"', '"Then what\'s the point of calling you?"'],
    answer: 0,
    hint: '상대가 확답은 피하면서도 노력하겠다고 한 부분을 이해하는 반응을 찾아보세요',
    explanation: '"I appreciate you trying"은 확답이 없어도 상대의 노력을 인정하는 성숙한 반응이에요.',
  },
  {
    id: 'doctor_32',
    category: 'doctor',
    type: 'meaning',
    difficulty: 'hard',
    situation: '병원 청구서 관련 통화에서 담당자가',
    phrase: 'It looks like there\'s a discrepancy on our end, let me sort that out.',
    choices: ['저희 쪽에서 차이가 있는 것 같으니 제가 바로잡아볼게요', '저희 쪽 말이 서로 다르니 정렬해서 보여드릴게요', '저희 실수를 손님이 정리해주셔야 해요'],
    answer: 0,
    hint: '"discrepancy"는 "불일치, 차이"를 뜻하고, "sort out"은 "해결하다"는 뜻이에요',
    explanation: '담당자 쪽 시스템에 오류/불일치가 있어서, 그걸 자신이 직접 해결하겠다는 뜻이에요.',
  },
  {
    id: 'work_01',
    category: 'work',
    type: 'meaning',
    difficulty: 'easy',
    situation: '동료와 복도에서 마주쳤을 때',
    phrase: 'How\'s it going?',
    choices: ['요즘 어떻게 지내요?', '어디로 가고 있어요?', '얼마나 걸려요?'],
    answer: 0,
    hint: '안부를 묻는 아주 흔한 인사예요',
    explanation: '실제 대답을 깊이 기대하지 않는 가벼운 인사 표현이에요.',
  },
  {
    id: 'work_02',
    category: 'work',
    type: 'meaning',
    difficulty: 'easy',
    situation: '상사가 회의 시작 전에',
    phrase: 'Let\'s dive right in.',
    choices: ['바로 시작합시다', '잠깐 쉬었다 갑시다', '다음에 다시 합시다'],
    answer: 0,
    hint: '"dive in"은 물에 뛰어든다는 뜻에서 나온 표현이에요',
    explanation: '지체 없이 바로 본론으로 들어가자는 뜻이에요.',
  },
  {
    id: 'work_03',
    category: 'work',
    type: 'meaning',
    difficulty: 'medium',
    situation: '팀 회의 중',
    phrase: 'Let\'s table this for now.',
    choices: ['이건 지금 테이블 위에 놓읍시다', '이건 지금 논의를 미룹시다', '이건 지금 표로 정리합시다'],
    answer: 1,
    hint: '"table"이 동사로 쓰이면 회의 안건을 다루는 방식과 관련 있어요',
    explanation: '"table this"는 지금 다루지 않고 나중으로 미룬다는 뜻이에요.',
  },
  {
    id: 'work_04',
    category: 'work',
    type: 'response',
    difficulty: 'easy',
    situation: '동료가 "How was your weekend?"라고 물었어요. 평범했을 때 자연스러운 대답은?',
    choices: ['"Pretty good, nothing too exciting."', '"It was good, nothing was very exciting."', '"I had a good weekend without excitement."'],
    answer: 0,
    hint: '짧고 캐주얼하게 답하는 게 자연스러워요',
    explanation: '"nothing too exciting"은 평범했다는 뜻을 캐주얼하게 전달하는 흔한 표현이에요.',
  },
  {
    id: 'work_05',
    category: 'work',
    type: 'meaning',
    difficulty: 'easy',
    situation: '상사가 프로젝트 마감을 알리며',
    phrase: 'This is due by end of day Friday.',
    choices: ['금요일 업무 종료까지 마감이에요', '금요일부터 시작하는 일이에요', '금요일에 하루종일 해야 해요'],
    answer: 0,
    hint: '"end of day"는 그날 업무 마감 시간을 뜻해요',
    explanation: '금요일 업무 시간이 끝나기 전까지 제출해야 한다는 뜻이에요.',
  },
  {
    id: 'work_06',
    category: 'work',
    type: 'response',
    difficulty: 'easy',
    situation: '상사가 "Can you send that over when you get a chance?"라고 했어요. 지금 바로 할 수 있을 때 자연스러운 대답은?',
    choices: ['"Sure, I\'ll send it now."', '"Yes, I will send it as soon as possible."', '"Okay, I have the chance now."'],
    answer: 0,
    hint: '짧고 캐주얼하게 지금 하겠다고 답하면 돼요',
    explanation: '"I\'ll send it now"가 자연스럽고 간단한 대답이에요.',
  },
  {
    id: 'work_07',
    category: 'work',
    type: 'meaning',
    difficulty: 'medium',
    situation: '동료가 프로젝트 관련',
    phrase: 'I\'ll loop you in on the next update.',
    choices: ['다음 업데이트 때 당신을 고리로 묶을게요', '다음 업데이트 내용을 당신도 포함해서 공유할게요', '다음 업데이트는 당신이 돌려서 확인해요'],
    answer: 1,
    hint: '"loop in"은 정보 공유 대상에 포함시킨다는 뜻이에요',
    explanation: '"loop someone in"은 그 사람도 정보를 받는 대상에 포함시키겠다는 관용 표현이에요.',
  },
  {
    id: 'work_08',
    category: 'work',
    type: 'fillBlank',
    difficulty: 'easy',
    situation: '회의 참석 여부를 물을 때',
    phrase: 'Are you available ___ 3pm?',
    choices: ['at', 'on', 'in'],
    answer: 0,
    hint: '정확한 시각 앞에 쓰는 전치사예요',
    explanation: '구체적인 시각 앞에는 "at"을 써요.',
  },
  {
    id: 'work_09',
    category: 'work',
    type: 'meaning',
    difficulty: 'medium',
    situation: '상사가 피드백을 주며',
    phrase: 'There\'s definitely room for improvement here.',
    choices: ['여기 개선할 여지가 확실히 있어요', '여기 방을 개선해야 해요', '여기는 확실히 개선이 불가능해요'],
    answer: 0,
    hint: '"room"은 물리적 공간이 아니라 "여지"라는 뜻으로도 쓰여요',
    explanation: '지금보다 더 나아질 수 있는 부분이 있다는 완곡한 지적이에요.',
  },
  {
    id: 'work_10',
    category: 'work',
    type: 'response',
    difficulty: 'medium',
    situation: '팀장이 "This isn\'t quite what I had in mind, but let\'s talk through it."라고 했어요. 가장 적절한 반응은?',
    choices: ['"Sure, happy to walk through my thinking."', '"Oh, so it\'s wrong?"', '"I did exactly what was asked."'],
    answer: 0,
    hint: '팀장이 "얘기해보자"고 한 건 비난이 아니라 대화의 시작이에요',
    explanation: '완곡한 피드백에 방어적으로 반응하기보다, 열린 태도로 대화를 이어가는 게 자연스러워요.',
  },
  {
    id: 'work_11',
    category: 'work',
    type: 'tone',
    difficulty: 'easy',
    situation: '팀장이 마감을 못 지킨 팀원에게 두 가지로 말했어요. 어느 쪽이 더 실망한 느낌일까요?',
    phraseA: 'No big deal, we\'ll adjust the timeline.',
    phraseB: 'I was really counting on this being done.',
    answer: 'B',
    hint: '"counting on"이 담고 있는 기대와 실망의 정도를 생각해보세요',
    explanation: 'A는 정말 괜찮다는 여유로운 반응, B는 기대했던 걸 강조하며 은근히 서운함을 드러내는 뉘앙스예요.',
  },
  {
    id: 'work_12',
    category: 'work',
    type: 'meaning',
    difficulty: 'easy',
    situation: '동료가 도움을 준 후',
    phrase: 'I owe you one.',
    choices: ['저는 당신에게 하나 빚졌어요', '저는 당신에게 하나 줄게요', '저는 당신 것 하나가 필요해요'],
    answer: 0,
    hint: '"owe"는 빚졌다는 뜻이에요',
    explanation: '도움을 받아서 나중에 갚아야 할 신세를 졌다는 뜻의 캐주얼한 감사 표현이에요.',
  },
  {
    id: 'work_13',
    category: 'work',
    type: 'meaning',
    difficulty: 'medium',
    situation: '상사가 회의에서',
    phrase: 'Let\'s circle back to this next week.',
    choices: ['이건 다음 주에 다시 얘기합시다', '이건 다음 주에 돌려드릴게요', '이건 다음 주에 원을 그려서 설명할게요'],
    answer: 0,
    hint: '"circle back"은 나중에 다시 돌아온다는 뜻이에요',
    explanation: '지금은 넘어가고 다음 주에 다시 논의하자는 뜻이에요.',
  },
  {
    id: 'work_14',
    category: 'work',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '동료에게 의견을 조심스럽게 제안할 때',
    phrase: 'I might be wrong, but ___ we try a different approach?',
    choices: ['what if', 'how about', 'what about'],
    answer: 0,
    hint: '"만약 ~하면 어떨까요"라는 조심스러운 제안 표현이에요',
    explanation: '"what if we try~"는 자기 의견을 강요하지 않고 부드럽게 제안하는 표현이에요.',
  },
  {
    id: 'work_15',
    category: 'work',
    type: 'tone',
    difficulty: 'medium',
    situation: '팀원 둘이 같은 업무 지연에 대해 상사에게 두 가지로 설명했어요. 어느 쪽이 더 남 탓하는 느낌일까요?',
    phraseA: 'I underestimated how long this would take.',
    phraseB: 'The other team didn\'t get me what I needed in time.',
    answer: 'B',
    hint: '누가 스스로의 책임을 인정하고, 누가 원인을 외부로 돌리는지 보세요',
    explanation: 'A는 자기 판단 부족을 인정하는 태도, B는 지연 원인을 다른 팀 탓으로 돌리는 뉘앙스예요.',
  },
  {
    id: 'work_16',
    category: 'work',
    type: 'response',
    difficulty: 'medium',
    situation: '상사가 "I know it\'s short notice, but could you handle this by tomorrow?"라고 물었어요. 가능할 때 가장 자연스러운 대답은?',
    choices: ['"Yeah, I can make that work."', '"Yes, I am able to do that."', '"Okay, I will handle it by tomorrow."'],
    answer: 0,
    hint: '캐주얼한 부탁엔 캐주얼한 짧은 답이 자연스러워요',
    explanation: '"I can make that work"는 어려운 요청도 맞춰보겠다는 자연스러운 캐주얼 표현이에요.',
  },
  {
    id: 'work_17',
    category: 'work',
    type: 'meaning',
    difficulty: 'medium',
    situation: '동료가 프로젝트에 대해',
    phrase: 'Let\'s not reinvent the wheel here.',
    choices: ['여기서 바퀴를 다시 만들지는 맙시다', '여기서 이미 있는 걸 처음부터 다시 만들진 맙시다', '여기서 바퀴 모양의 아이디어는 빼요'],
    answer: 1,
    hint: '"reinvent the wheel"은 이미 있는 걸 불필요하게 다시 만든다는 관용 표현이에요',
    explanation: '이미 검증된 방법이 있는데 굳이 처음부터 새로 만들 필요는 없다는 뜻이에요.',
  },
  {
    id: 'work_18',
    category: 'work',
    type: 'tone',
    difficulty: 'medium',
    situation: '팀장이 새 아이디어에 대해 두 가지로 반응했어요. 어느 쪽이 더 회의적인 느낌일까요?',
    phraseA: 'I love this direction, let\'s build on it.',
    phraseB: 'It\'s definitely... a bold idea.',
    answer: 'B',
    hint: '"bold"라는 단어가 칭찬으로 쓰였는지, 돌려 말하는 지적으로 쓰였는지 생각해보세요',
    explanation: 'A는 명확한 지지, B는 말줄임표와 "bold"(과감한)라는 애매한 단어로 우회적으로 부정적 뉘앙스를 전달해요.',
  },
  {
    id: 'work_19',
    category: 'work',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '회의에서 의견에 동의하지만 조건을 달 때',
    phrase: 'I\'m on board with this, ___ we adjust the timeline a bit.',
    choices: ['as long as', 'even if', 'unless'],
    answer: 0,
    hint: '"~하는 한, ~라는 조건이라면"이라는 뜻이에요',
    explanation: '"as long as"는 조건부 동의를 나타낼 때 자주 쓰이는 표현이에요.',
  },
  {
    id: 'work_20',
    category: 'work',
    type: 'meaning',
    difficulty: 'hard',
    situation: '상사가 프로젝트 우선순위를 정하며',
    phrase: 'This isn\'t a hill I want to die on.',
    choices: ['이건 제가 죽어도 지키고 싶은 언덕이 아니에요', '이건 제가 끝까지 고집할 만큼 중요한 문제는 아니에요', '이건 언덕 위에서 논의해야 할 만큼 큰일이에요'],
    answer: 1,
    hint: '"a hill to die on"은 목숨 걸고 싸울 만한 문제라는 관용 표현이에요',
    explanation: '"not a hill I want to die on"은 이 문제로 끝까지 강하게 주장하고 싶지는 않다는 뜻이에요.',
  },
  {
    id: 'work_21',
    category: 'work',
    type: 'response',
    difficulty: 'medium',
    situation: '동료가 "I hate to ask, but could you cover my shift tomorrow?"라고 물었어요. 가능할 때 자연스러운 대답은?',
    choices: ['"No worries, I\'ve got you."', '"It\'s okay, I will cover it for you."', '"Don\'t hate to ask, I can do it."'],
    answer: 0,
    hint: '캐주얼한 부탁엔 캐주얼한 표현으로 화답하는 게 자연스러워요',
    explanation: '"I\'ve got you"는 "내가 처리해줄게, 걱정 마"라는 뜻의 아주 흔한 캐주얼 표현이에요.',
  },
  {
    id: 'work_22',
    category: 'work',
    type: 'meaning',
    difficulty: 'hard',
    situation: '상사가 팀원 평가에 대해',
    phrase: 'He\'s a bit of a wild card on this project.',
    choices: ['그는 이 프로젝트에서 좀 예측하기 어려운 사람이에요', '그는 이 프로젝트에서 카드 게임을 좋아해요', '그는 이 프로젝트의 가장 뛰어난 사람이에요'],
    answer: 0,
    hint: '"wild card"는 카드 게임에서 유래한 관용 표현이에요',
    explanation: '"wild card"는 예측 불가능하거나 어떻게 될지 모르는 사람/요소를 뜻하는 관용 표현이에요.',
  },
  {
    id: 'work_23',
    category: 'work',
    type: 'tone',
    difficulty: 'hard',
    situation: '팀원이 실수에 대해 상사에게 설명하며 두 가지로 말했어요. 어느 쪽이 더 진심으로 반성하는 느낌일까요?',
    phraseA: 'That\'s on me, I should\'ve double-checked before sending it.',
    phraseB: 'Well, nobody flagged it before it went out either.',
    answer: 'A',
    hint: '누가 자기 책임을 온전히 인정하고, 누가 다른 사람 탓도 슬쩍 섞는지 보세요',
    explanation: 'A는 자기 잘못을 명확히 인정하는 태도, B는 다른 사람도 안 걸러냈다며 은근히 책임을 분산시키는 뉘앙스예요.',
  },
  {
    id: 'work_24',
    category: 'work',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '상사에게 조심스럽게 다른 의견을 제시할 때',
    phrase: 'I see your point, but I ___ see it a bit differently.',
    choices: ['kind of', 'kind', 'kinds of'],
    answer: 0,
    hint: '"약간, 어느 정도"라는 뜻으로 의견을 부드럽게 만드는 표현이에요',
    explanation: '"kind of"는 발언을 부드럽게 완화하는 아주 흔한 캐주얼 표현이에요.',
  },
  {
    id: 'work_25',
    category: 'work',
    type: 'meaning',
    difficulty: 'hard',
    situation: '동료가 프로젝트 진행 상황에 대해',
    phrase: 'We\'re not out of the woods yet.',
    choices: ['우리는 아직 숲에서 안 나왔어요', '우리는 아직 위기를 완전히 벗어난 게 아니에요', '우리는 숲처럼 복잡한 상황이에요'],
    answer: 1,
    hint: '"out of the woods"는 어려운 상황을 벗어났다는 관용 표현이에요',
    explanation: '"not out of the woods yet"은 상황이 나아지고 있어도 아직 완전히 안심할 단계는 아니라는 뜻이에요.',
  },
  {
    id: 'work_26',
    category: 'work',
    type: 'tone',
    difficulty: 'hard',
    situation: '상사가 팀원의 승진 요청에 대해 두 가지로 답했어요. 어느 쪽이 더 실질적으로는 거절에 가까울까요?',
    phraseA: 'Let\'s definitely talk about that in your next review.',
    phraseB: 'That\'s something we can look into down the road.',
    answer: 'B',
    hint: '어느 쪽이 구체적인 시점을 제시하고, 어느 쪽이 막연하게 미루는지 보세요',
    explanation: 'A는 구체적인 시점(다음 리뷰)을 제시하며 진지하게 논의할 의지를 보임, B는 "언젠가"라는 막연한 표현으로 확답을 피하며 사실상 미루는 뉘앙스예요.',
  },
  {
    id: 'work_27',
    category: 'work',
    type: 'response',
    difficulty: 'hard',
    situation: '상사가 프로젝트 방향에 대해 "I\'m not 100% sold on this yet, but I\'m willing to hear more."라고 했어요. 가장 적절한 반응은?',
    choices: ['"Got it, let me put together a stronger case."', '"So does that mean it\'s approved?"', '"Why aren\'t you convinced already?"'],
    answer: 0,
    hint: '"not 100% sold"가 완전한 거절도 완전한 승인도 아니라는 걸 이해하는 반응을 찾아보세요',
    explanation: '상사가 열린 태도를 보이되 아직 확신은 없다는 뉘앙스를 정확히 읽고, 설득 기회로 받아들이는 반응이 자연스러워요.',
  },
  {
    id: 'work_28',
    category: 'work',
    type: 'fillBlank',
    difficulty: 'hard',
    situation: '회의에서 민감한 주제를 조심스럽게 꺼낼 때',
    phrase: 'I don\'t ___ to bring this up, but we might be behind schedule.',
    choices: ['mean', 'want', 'like'],
    answer: 0,
    hint: '"이런 말을 하려는 의도는 아니지만"이라는 뜻의 완곡 표현이에요',
    explanation: '"I don\'t mean to bring this up, but..."은 부정적이거나 민감한 얘기를 꺼내기 전에 쓰는 대표적인 완곡 표현이에요.',
  },
  {
    id: 'work_29',
    category: 'work',
    type: 'tone',
    difficulty: 'hard',
    situation: '동료 둘이 팀장의 새 정책에 대해 두 가지로 말했어요. 어느 쪽이 더 불만이 있는 느낌일까요?',
    phraseA: 'It makes sense, I get why we\'re doing this.',
    phraseB: 'Sure, if that\'s what they want to do.',
    answer: 'B',
    hint: '누가 정책을 진심으로 이해하고, 누가 거리를 두며 마지못해 받아들이는지 보세요',
    explanation: 'A는 정책의 이유를 이해하고 받아들이는 태도, B는 "그들이 원한다면"이라며 거리를 두고 마지못해 따르는 듯한 뉘앙스예요.',
  },
  {
    id: 'work_30',
    category: 'work',
    type: 'fillBlank',
    difficulty: 'hard',
    situation: '상사에게 실수를 보고하며 조심스럽게 인정할 때',
    phrase: 'I think I might ___ misread the instructions.',
    choices: ['have', 'has', 'had'],
    answer: 0,
    hint: '"might have p.p."는 과거 일을 조심스럽게 추측/인정하는 구조예요',
    explanation: '"might have misread"는 "잘못 이해했을 수도 있다"는 뜻으로, 실수를 부드럽게 인정하는 표현이에요.',
  },
  {
    id: 'work_31',
    category: 'work',
    type: 'response',
    difficulty: 'hard',
    situation: '상사가 예산 삭감에 대해 "I wish I had better news, but we\'ll need to make some cuts."라고 했어요. 가장 적절한 반응은?',
    choices: ['"I appreciate you being straightforward about it."', '"So how bad is it really?"', '"Couldn\'t you have prevented this?"'],
    answer: 0,
    hint: '상사가 어려운 소식을 조심스럽게 전한 태도를 인정하는 반응을 찾아보세요',
    explanation: '힘든 소식을 솔직하게 전달한 것에 대해 감사를 표하는 게 성숙하고 자연스러운 반응이에요.',
  },
  {
    id: 'work_32',
    category: 'work',
    type: 'meaning',
    difficulty: 'hard',
    situation: '동료가 프로젝트 리스크에 대해',
    phrase: 'I don\'t want to jump the gun, but this timeline seems tight.',
    choices: ['괜한 걱정을 하고 싶지는 않지만, 일정이 빠듯해 보여요', '성급하게 결론 내리고 싶지는 않지만, 일정이 빠듯해 보여요', '남 탓을 하고 싶지는 않지만, 일정이 빠듯해 보여요'],
    answer: 1,
    hint: '"jump the gun"은 육상 경기에서 총소리가 나기 전에 미리 출발하는 반칙에서 유래한 표현이에요',
    explanation: '"jump the gun"은 "때가 되기 전에 성급하게 행동/판단하다"라는 뜻이에요. 나머지 오답들은 걱정이나 책임 전가 등 다른 방향의 뜻이라 헷갈리기 쉬워요.',
  },
  {
    id: 'smalltalk_01',
    category: 'smalltalk',
    type: 'meaning',
    difficulty: 'easy',
    situation: '엘리베이터에서 이웃과',
    phrase: 'Long time no see!',
    choices: ['오랜만이에요!', '시간이 얼마 안 남았어요!', '오래 걸리진 않을 거예요!'],
    answer: 0,
    hint: '아주 흔한 재회 인사예요',
    explanation: '오랜만에 만난 사람에게 하는 캐주얼한 인사 표현이에요.',
  },
  {
    id: 'smalltalk_02',
    category: 'smalltalk',
    type: 'meaning',
    difficulty: 'easy',
    situation: '처음 만난 사람과',
    phrase: 'What do you do?',
    choices: ['무슨 일 하세요?', '뭘 하고 계세요?', '뭘 드시겠어요?'],
    answer: 0,
    hint: '직업을 묻는 아주 흔한 스몰토크 질문이에요',
    explanation: '"What do you do (for a living)?"의 줄임말로, 직업을 묻는 표현이에요.',
  },
  {
    id: 'smalltalk_03',
    category: 'smalltalk',
    type: 'meaning',
    difficulty: 'medium',
    situation: '이웃과 마주쳤을 때',
    phrase: 'We should catch up sometime.',
    choices: ['우리 언제 한번 서로 근황 얘기해요', '우리 언제 한번 따라잡기 게임해요', '우리 언제 한번 만나서 뛰어요'],
    answer: 0,
    hint: '"catch up"은 밀린 이야기를 나눈다는 뜻이에요',
    explanation: '오랜만에 만난 사람과 근황을 나누자는 캐주얼한 제안이에요.',
  },
  {
    id: 'smalltalk_04',
    category: 'smalltalk',
    type: 'response',
    difficulty: 'easy',
    situation: '이웃이 "How\'s your family doing?"이라고 물었어요. 다들 잘 지낼 때 자연스러운 대답은?',
    choices: ['"They\'re doing great, thanks for asking!"', '"They are doing very well currently."', '"My family is fine at this time."'],
    answer: 0,
    hint: '캐주얼한 질문엔 캐주얼한 대답이 자연스러워요',
    explanation: '"doing great, thanks for asking"이 가장 흔하고 자연스러운 대답이에요.',
  },
  {
    id: 'smalltalk_05',
    category: 'smalltalk',
    type: 'meaning',
    difficulty: 'easy',
    situation: '처음 만난 사람과 헤어질 때',
    phrase: 'It was nice meeting you!',
    choices: ['만나서 반가웠어요!', '저를 만나주셔서 감사해요!', '다시 만나고 싶어요!'],
    answer: 0,
    hint: '헤어질 때 하는 인사 표현이에요',
    explanation: '처음 만난 사람과 헤어질 때 하는 표준 인사예요.',
  },
  {
    id: 'smalltalk_06',
    category: 'smalltalk',
    type: 'response',
    difficulty: 'easy',
    situation: '이웃이 "Nice weather we\'re having, huh?"라고 말했어요. 동의할 때 자연스러운 대답은?',
    choices: ['"Yeah, it\'s beautiful out."', '"Yes, we are having nice weather."', '"I agree that the weather is nice."'],
    answer: 0,
    hint: '날씨 얘기엔 짧고 캐주얼하게 맞장구치는 게 자연스러워요',
    explanation: '"it\'s beautiful out"은 날씨 스몰토크에 자연스럽게 맞장구치는 흔한 표현이에요.',
  },
  {
    id: 'smalltalk_07',
    category: 'smalltalk',
    type: 'meaning',
    difficulty: 'medium',
    situation: '파티에서 처음 만난 사람과',
    phrase: 'So, what brings you here?',
    choices: ['그래서, 여기 어떻게 오셨어요?', '그래서, 여기서 뭘 가져오셨어요?', '그래서, 여기 얼마나 걸려서 오셨어요?'],
    answer: 0,
    hint: '"what brings you"는 물건이 아니라 이유를 묻는 표현이에요',
    explanation: '이 자리/장소에 오게 된 계기를 묻는 자연스러운 스몰토크 질문이에요.',
  },
  {
    id: 'smalltalk_08',
    category: 'smalltalk',
    type: 'fillBlank',
    difficulty: 'easy',
    situation: '오랜만에 만난 사람에게',
    phrase: 'It\'s been a while, hasn\'t ___ ?',
    choices: ['it', 'that', 'this'],
    answer: 0,
    hint: '부가의문문에서 "it"을 다시 받는 형태예요',
    explanation: '"It\'s been a while, hasn\'t it?"은 부가의문문 구조로, "it"을 그대로 받는 게 문법적으로 맞아요.',
  },
  {
    id: 'smalltalk_09',
    category: 'smalltalk',
    type: 'meaning',
    difficulty: 'medium',
    situation: '이웃이 새로 이사온 사람에게',
    phrase: 'Feel free to stop by anytime.',
    choices: ['언제든 편하게 들르세요', '언제든 멈춰서 서 계세요', '아무 때나 잠깐 서 있어도 돼요'],
    answer: 0,
    hint: '"stop by"는 짧게 방문한다는 뜻이에요',
    explanation: '격식 없이 언제든 편하게 놀러 오라는 친근한 표현이에요.',
  },
  {
    id: 'smalltalk_10',
    category: 'smalltalk',
    type: 'response',
    difficulty: 'medium',
    situation: '새로 만난 이웃이 "We should get the families together sometime!"이라고 했어요. 가장 적절한 반응은?',
    choices: ['"That\'d be lovely, let\'s figure out a time."', '"Okay, when exactly?"', '"Sure, I\'ll wait for you to plan it."'],
    answer: 0,
    hint: '"sometime" 같은 캐주얼한 제안엔 비슷한 톤으로 화답하는 게 자연스러워요',
    explanation: '캐주얼한 제안을 편하게 받아들이면서도 관심을 보이는 반응이 가장 자연스러워요.',
  },
  {
    id: 'smalltalk_11',
    category: 'smalltalk',
    type: 'tone',
    difficulty: 'easy',
    situation: '이웃 둘이 파티 초대에 대해 두 가지로 말했어요. 어느 쪽이 더 진심으로 반가워하는 느낌일까요?',
    phraseA: 'Oh, that sounds fun, count me in!',
    phraseB: 'Oh, sure, maybe.',
    answer: 'A',
    hint: '"count me in"과 "maybe"가 담긴 확신의 정도를 비교해보세요',
    explanation: 'A는 적극적인 수락 표현, B는 "maybe"로 애매하게 발을 빼는 뉘앙스예요.',
  },
  {
    id: 'smalltalk_12',
    category: 'smalltalk',
    type: 'meaning',
    difficulty: 'easy',
    situation: '처음 만난 사람과 대화 중',
    phrase: 'Small world!',
    choices: ['세상 참 좁네요!', '세상이 작아지고 있어요!', '작은 세상을 만들어봐요!'],
    answer: 0,
    hint: '뜻밖의 공통점을 발견했을 때 쓰는 표현이에요',
    explanation: '의외의 공통 지인/경험을 발견했을 때 놀라며 하는 표현이에요.',
  },
  {
    id: 'smalltalk_13',
    category: 'smalltalk',
    type: 'meaning',
    difficulty: 'medium',
    situation: '동네 카페에서 안면 있는 사람과',
    phrase: 'I feel like I haven\'t seen you in ages.',
    choices: ['정말 오랜만에 뵙는 것 같아요', '당신을 나이 들어서 본 것 같아요', '당신을 시대별로 본 것 같아요'],
    answer: 0,
    hint: '"in ages"는 "아주 오랫동안"이라는 뜻이에요',
    explanation: '"in ages"는 나이나 시대와 상관없이 "오랫동안"을 뜻하는 캐주얼한 표현이에요.',
  },
  {
    id: 'smalltalk_14',
    category: 'smalltalk',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '상대방 근황을 조심스럽게 물어볼 때',
    phrase: 'I don\'t want to pry, but how ___ things going with the move?',
    choices: ['are', 'is', 'was'],
    answer: 0,
    hint: '"things"가 복수라 동사도 그에 맞춰야 해요',
    explanation: '"things"는 복수 취급이라 "are"가 문법적으로 맞아요.',
  },
  {
    id: 'smalltalk_15',
    category: 'smalltalk',
    type: 'tone',
    difficulty: 'medium',
    situation: '이웃 둘이 서로의 최근 소식에 대해 두 가지로 반응했어요. 어느 쪽이 더 형식적으로(진심 없이) 들릴까요?',
    phraseA: 'Oh wow, that\'s amazing, tell me everything!',
    phraseB: 'Oh, that\'s nice.',
    answer: 'B',
    hint: '반응의 길이와 후속 질문 여부가 관심의 정도를 보여줘요',
    explanation: 'A는 구체적인 관심과 열정을 보이는 반응, B는 짧고 무미건조해서 사실 별로 관심 없어 보이는 뉘앙스예요.',
  },
  {
    id: 'smalltalk_16',
    category: 'smalltalk',
    type: 'response',
    difficulty: 'medium',
    situation: '이웃이 "You look really familiar, have we met before?"라고 물었어요. 정말 처음 만나는 거라면 가장 자연스러운 대답은?',
    choices: ['"I don\'t think so, but maybe I just have one of those faces!"', '"No, we have never met before."', '"That is incorrect, we haven\'t met."'],
    answer: 0,
    hint: '캐주얼한 스몰토크엔 가볍고 유머러스한 반응이 자연스러워요',
    explanation: '"one of those faces"는 "흔한 인상이라 낯익어 보일 수 있다"는 뜻의 유쾌한 표현이에요.',
  },
  {
    id: 'smalltalk_17',
    category: 'smalltalk',
    type: 'meaning',
    difficulty: 'medium',
    situation: '오랜만에 만난 지인이',
    phrase: 'You haven\'t changed a bit!',
    choices: ['하나도 안 변하셨네요!', '조금도 안 바뀌셨네요, 아쉬워요!', '변화가 하나도 없어서 걱정이에요!'],
    answer: 0,
    hint: '"not changed a bit"은 부정적 의미가 아니에요',
    explanation: '세월이 지나도 그대로라는 긍정적인 칭찬 표현이에요.',
  },
  {
    id: 'smalltalk_18',
    category: 'smalltalk',
    type: 'tone',
    difficulty: 'medium',
    situation: '이웃 둘이 서로의 정원 가꾸기에 대해 두 가지로 말했어요. 어느 쪽이 더 은근히 비교/경쟁하는 느낌일까요?',
    phraseA: 'Your garden looks great this year!',
    phraseB: 'Your garden\'s looking good — mine\'s coming along too, actually.',
    answer: 'B',
    hint: '칭찬 뒤에 곧바로 자기 얘기를 붙이는 게 어떤 느낌을 주는지 생각해보세요',
    explanation: 'A는 순수한 칭찬, B는 칭찬 뒤에 자기 정원 얘기를 덧붙이며 은근히 비교하는 뉘앙스예요.',
  },
  {
    id: 'smalltalk_19',
    category: 'smalltalk',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '상대방의 근황을 듣고 공감을 표현할 때',
    phrase: 'That sounds like it\'s ___ a lot to deal with.',
    choices: ['been', 'being', 'be'],
    answer: 0,
    hint: '현재완료 구조로 "지금까지 계속 그래왔다"는 뜻을 나타내요',
    explanation: '"it\'s been a lot"은 "지금까지 계속 힘들었다"는 뜻의 현재완료 표현이에요.',
  },
  {
    id: 'smalltalk_20',
    category: 'smalltalk',
    type: 'meaning',
    difficulty: 'hard',
    situation: '이웃이 파티 초대에 대해',
    phrase: 'I\'ll try to swing by if I can.',
    choices: ['제가 갈 수 있으면 잠깐 들러볼게요', '제가 그네를 타고 넘어갈게요', '제가 확실히 참석할게요'],
    answer: 0,
    hint: '"swing by"는 짧게 들른다는 뜻의 관용 표현이에요',
    explanation: '"swing by"는 "잠깐 들르다"는 뜻이고, "try to ~ if I can"이 붙으면 확실한 약속이 아니라 가능하면 시도해보겠다는 낮은 확률의 표현이 돼요.',
  },
  {
    id: 'smalltalk_21',
    category: 'smalltalk',
    type: 'response',
    difficulty: 'medium',
    situation: '이웃이 "We\'re having people over Saturday, you should swing by if you\'re free!"라고 했어요. 갈 수 있을지 확실치 않을 때 자연스러운 대답은?',
    choices: ['"Thanks, I\'ll try to make it!"', '"Thank you, I will attempt to be present."', '"I don\'t know if I can come."'],
    answer: 0,
    hint: '캐주얼한 초대엔 캐주얼하고 긍정적인 뉘앙스로 답하는 게 자연스러워요',
    explanation: '"I\'ll try to make it"은 확답은 아니지만 긍정적으로 노력하겠다는 자연스러운 표현이에요.',
  },
  {
    id: 'smalltalk_22',
    category: 'smalltalk',
    type: 'meaning',
    difficulty: 'hard',
    situation: '지인이 최근 소식을 전하며',
    phrase: 'Long story short, we ended up moving.',
    choices: ['짧은 이야기지만, 결국 이사했어요', '길게 얘기하면 복잡한데, 결국 이사하게 됐어요', '이야기가 짧아서, 이사는 안 했어요'],
    answer: 1,
    hint: '"long story short"는 "자세한 건 생략하고 결론만 말하면"이라는 뜻이에요',
    explanation: '"long story short"는 복잡한 사연을 생략하고 결론만 간단히 전할 때 쓰는 관용 표현이에요.',
  },
  {
    id: 'smalltalk_23',
    category: 'smalltalk',
    type: 'tone',
    difficulty: 'hard',
    situation: '이웃 둘이 동네 소식에 대해 두 가지로 말했어요. 어느 쪽이 더 뒷말/험담에 가까운 느낌일까요?',
    phraseA: 'I heard they\'re renovating, that\'s exciting!',
    phraseB: 'I heard they\'re renovating — again. Third time this year.',
    answer: 'B',
    hint: '사실을 그냥 전달하는 것과, 특정 단어를 강조해서 비꼬는 것의 차이를 보세요',
    explanation: 'A는 순수한 관심과 긍정적 반응, B는 "또"와 "올해 세 번째"를 강조하며 은근히 비꼬는 뉘앙스예요.',
  },
  {
    id: 'smalltalk_24',
    category: 'smalltalk',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '이웃에게 부담 없이 안부를 물을 때',
    phrase: 'No pressure, but I was wondering ___ things were going.',
    choices: ['how', 'what', 'that'],
    answer: 0,
    hint: '상태/근황을 물을 때 쓰는 의문사예요',
    explanation: '"how things were going"은 "어떻게 지내는지"를 묻는 자연스러운 표현이에요.',
  },
  {
    id: 'smalltalk_25',
    category: 'smalltalk',
    type: 'meaning',
    difficulty: 'hard',
    situation: '지인이 최근 힘든 일에 대해',
    phrase: 'I don\'t want to make a big deal out of it, but it\'s been rough.',
    choices: ['큰 거래를 만들고 싶지는 않지만, 힘들었어요', '크게 부풀리고 싶지는 않지만, 힘들었어요', '큰 사업을 시작하고 싶지는 않지만, 힘들었어요'],
    answer: 1,
    hint: '"make a big deal"은 사업 거래와 관련 없는 관용 표현이에요',
    explanation: '"make a big deal out of it"은 "별일 아닌 것처럼 부풀리지 않겠다"는 뜻의 관용 표현이에요.',
  },
  {
    id: 'smalltalk_26',
    category: 'smalltalk',
    type: 'tone',
    difficulty: 'hard',
    situation: '이웃 둘이 서로의 최근 승진 소식에 대해 두 가지로 반응했어요. 어느 쪽이 더 진심으로 축하하지 않는 느낌일까요?',
    phraseA: 'That\'s incredible, you totally deserve it!',
    phraseB: 'Oh wow, good for you.',
    answer: 'B',
    hint: '"good for you"가 상황에 따라 진심 어린 축하일 수도, 건조한 반응일 수도 있다는 걸 생각해보세요',
    explanation: 'A는 구체적이고 열정적인 축하, B는 "good for you"라는 짧고 상투적인 표현으로 형식적인 축하만 건네는 뉘앙스예요.',
  },
  {
    id: 'smalltalk_27',
    category: 'smalltalk',
    type: 'response',
    difficulty: 'hard',
    situation: '지인이 최근 이혼 소식을 전하며 "It\'s been a lot, but I\'m doing okay, I think."라고 했어요. 가장 적절한 반응은?',
    choices: ['"That makes sense, take all the time you need."', '"That\'s great that you\'re okay!"', '"What exactly happened?"'],
    answer: 0,
    hint: '"I think"라는 표현에 담긴 조심스러움과 불확실함을 존중하는 반응을 찾아보세요',
    explanation: '상대가 완전히 괜찮다고 확신하지 못하는 뉘앙스를 존중하며, 공간을 주는 반응이 가장 자연스러워요.',
  },
  {
    id: 'smalltalk_28',
    category: 'smalltalk',
    type: 'fillBlank',
    difficulty: 'hard',
    situation: '어색한 화제를 조심스럽게 바꾸고 싶을 때',
    phrase: 'Anyway, not to change the subject, but ___ you seen the new café down the street?',
    choices: ['have', 'did', 'do'],
    answer: 0,
    hint: '경험을 물을 때 쓰는 현재완료 의문문 구조예요',
    explanation: '"Have you seen ~?"은 경험 여부를 묻는 자연스러운 현재완료 구조예요.',
  },
  {
    id: 'smalltalk_29',
    category: 'smalltalk',
    type: 'tone',
    difficulty: 'hard',
    situation: '이웃 둘이 서로의 반려동물에 대해 두 가지로 말했어요. 어느 쪽이 더 은근히 불편함을 드러내는 느낌일까요?',
    phraseA: 'Your dog is so full of energy, I love it!',
    phraseB: 'Your dog sure has a lot of energy, huh.',
    answer: 'B',
    hint: '감탄사 "huh"가 순수한 관찰인지, 돌려 말하는 불만인지 생각해보세요',
    explanation: 'A는 명확한 긍정적 칭찬, B는 "huh"라는 애매한 추임새로 사실은 불편함(예: 짖음, 흥분)을 완곡하게 지적하는 뉘앙스예요.',
  },
  {
    id: 'smalltalk_30',
    category: 'smalltalk',
    type: 'fillBlank',
    difficulty: 'hard',
    situation: '오랜만에 만난 사람에게 근황이 잘 기억 안 난다고 조심스럽게 말할 때',
    phrase: 'I feel bad, I think I might ___ forgotten what you do for work.',
    choices: ['have', 'has', 'had'],
    answer: 0,
    hint: '"might have p.p."는 조심스러운 인정/추측을 나타내는 구조예요',
    explanation: '"might have forgotten"은 "깜빡했을 수도 있다"는 뜻으로, 미안함을 부드럽게 표현하는 방식이에요.',
  },
  {
    id: 'smalltalk_31',
    category: 'smalltalk',
    type: 'response',
    difficulty: 'hard',
    situation: '지인이 최근 근황을 전하며 "I don\'t really want to get into it right now, but things have been kind of a lot."이라고 했어요. 가장 적절한 반응은?',
    choices: ['"Totally understand, I\'m here whenever you want to talk."', '"What\'s going on? You can tell me."', '"That sounds bad, what happened?"'],
    answer: 0,
    hint: '상대가 "지금은 얘기하고 싶지 않다"고 분명히 말한 의사를 존중하는 반응을 찾아보세요',
    explanation: '상대의 경계를 존중하면서도 지지를 표현하는 반응이 가장 성숙하고 자연스러워요.',
  },
  {
    id: 'smalltalk_32',
    category: 'smalltalk',
    type: 'meaning',
    difficulty: 'hard',
    situation: '지인이 최근 관계에 대해',
    phrase: 'We\'re kind of on and off, it\'s complicated.',
    choices: ['우리는 스위치를 켰다 껐다 하는 사이예요, 복잡해요', '우리는 만났다 헤어졌다 하는 사이예요, 복잡해요', '우리는 가끔씩만 연락하는 사이예요, 복잡해요'],
    answer: 1,
    hint: '"on and off"는 전자기기의 전원과는 무관한 관계 관련 관용 표현이에요',
    explanation: '"on and off"는 관계가 이어졌다 끊어졌다를 반복한다는 뜻의 관용 표현이에요.',
  },
  {
    id: 'school_01',
    category: 'school',
    type: 'meaning',
    difficulty: 'easy',
    situation: '교수님 오피스아워',
    phrase: 'Feel free to stop by if you have questions.',
    choices: ['질문 있으시면 편하게 오세요', '질문 있으시면 서서 기다리세요', '질문은 나중에 멈추고 물어보세요'],
    answer: 0,
    hint: '"stop by"는 짧게 들른다는 뜻이에요',
    explanation: '오피스아워 때 편하게 찾아와도 된다는 친근한 표현이에요.',
  },
  {
    id: 'school_02',
    category: 'school',
    type: 'meaning',
    difficulty: 'easy',
    situation: '강의 첫 시간',
    phrase: 'This is a lot to cover, so let\'s get started.',
    choices: ['다룰 내용이 많으니 바로 시작합시다', '이건 덮어야 할 게 많으니 나중에 합시다', '커버할 게 많아서 오늘은 쉽니다'],
    answer: 0,
    hint: '"cover"는 수업에서 "다루다, 배우다"라는 뜻으로도 쓰여요',
    explanation: '오늘 다뤄야 할 학습량이 많다는 뜻이에요.',
  },
  {
    id: 'school_03',
    category: 'school',
    type: 'meaning',
    difficulty: 'medium',
    situation: '조교가 과제에 대해',
    phrase: 'You can turn this in whenever, no strict deadline.',
    choices: ['이건 아무 때나 돌려서 내시면 돼요', '이건 엄격한 마감 없이 아무 때나 제출하시면 돼요', '이건 마감이 엄격하니 돌아서 제출하세요'],
    answer: 1,
    hint: '"turn in"은 과제를 제출한다는 뜻이에요',
    explanation: '"turn in"은 "제출하다"라는 뜻의 표현이고, 여기선 마감이 느슨하다는 안내예요.',
  },
  {
    id: 'school_04',
    category: 'school',
    type: 'response',
    difficulty: 'easy',
    situation: '교수님이 "Does that make sense?"라고 물었어요. 이해했을 때 자연스러운 대답은?',
    choices: ['"Yeah, that makes sense."', '"Yes, I understand the sense of it."', '"Yes, it has sense to me."'],
    answer: 0,
    hint: '캐주얼하게 짧게 답하면 돼요',
    explanation: '"that makes sense"는 이해했다는 뜻의 가장 흔한 표현이에요.',
  },
  {
    id: 'school_05',
    category: 'school',
    type: 'meaning',
    difficulty: 'easy',
    situation: '학교 행정실',
    phrase: 'You\'ll need to fill this out and bring it back.',
    choices: ['이거 작성하셔서 다시 가져오셔야 해요', '이거 채워서 버리셔야 해요', '이거 작성하시고 여기 두고 가세요'],
    answer: 0,
    hint: '"fill out"은 서류를 작성한다는 뜻이에요',
    explanation: '서류를 작성한 뒤 다시 제출하러 와야 한다는 안내예요.',
  },
  {
    id: 'school_06',
    category: 'school',
    type: 'response',
    difficulty: 'easy',
    situation: '조교가 "Are you following along okay?"라고 물었어요. 잘 따라가고 있을 때 자연스러운 대답은?',
    choices: ['"Yeah, I\'m good."', '"Yes, I am following well."', '"Yes, I follow along okay."'],
    answer: 0,
    hint: '짧고 캐주얼하게 답하면 충분해요',
    explanation: '"I\'m good"은 "괜찮다, 잘 따라가고 있다"는 뜻의 흔한 캐주얼 표현이에요.',
  },
  {
    id: 'school_07',
    category: 'school',
    type: 'meaning',
    difficulty: 'medium',
    situation: '교수님이 시험 범위에 대해',
    phrase: 'This won\'t be on the test, but it\'s good to know.',
    choices: ['이건 시험엔 안 나오지만 알아두면 좋아요', '이건 시험에 나올 거라서 알아둬야 해요', '이건 시험 문제로는 안 좋아요'],
    answer: 0,
    hint: '"won\'t be on the test"는 시험 범위가 아니라는 뜻이에요',
    explanation: '시험 출제 범위는 아니지만 배경지식으로 알아두면 좋다는 뜻이에요.',
  },
  {
    id: 'school_08',
    category: 'school',
    type: 'fillBlank',
    difficulty: 'easy',
    situation: '과제 제출 기한을 물을 때',
    phrase: 'When is this due ___?',
    choices: ['by', 'at', 'on'],
    answer: 0,
    hint: '"언제까지"라는 뜻의 전치사예요',
    explanation: '"due by (날짜)"는 "~까지 마감"이라는 뜻의 표현이에요.',
  },
  {
    id: 'school_09',
    category: 'school',
    type: 'meaning',
    difficulty: 'medium',
    situation: '교수님이 학생 질문에 답하며',
    phrase: 'That\'s a good question, let me think about it.',
    choices: ['좋은 질문이네요, 생각 좀 해볼게요', '좋은 질문이지만, 생각할 필요는 없어요', '좋은 질문은 이미 생각해봤어요'],
    answer: 0,
    hint: '진심으로 좋은 질문이라 평가한다는 뜻이에요',
    explanation: '즉답하기 어려운 질문에 대해 잠깐 생각할 시간을 갖겠다는 뜻이에요.',
  },
  {
    id: 'school_10',
    category: 'school',
    type: 'response',
    difficulty: 'medium',
    situation: '교수님이 "This paper needs some work, but the ideas are solid."라고 했어요. 가장 적절한 반응은?',
    choices: ['"Thank you, I\'ll revise it based on your feedback."', '"So it\'s bad?"', '"I thought it was already good."'],
    answer: 0,
    hint: '교수님이 지적과 칭찬을 같이 했다는 걸 이해하는 반응을 찾아보세요',
    explanation: '"needs some work"와 "ideas are solid"를 둘 다 인정하며 건설적으로 받아들이는 게 자연스러워요.',
  },
  {
    id: 'school_11',
    category: 'school',
    type: 'tone',
    difficulty: 'easy',
    situation: '교수님이 과제 제출이 늦은 학생에게 두 가지로 말했어요. 어느 쪽이 더 엄격하게 들릴까요?',
    phraseA: 'No worries, just get it to me when you can.',
    phraseB: 'This needs to be in by tomorrow, no exceptions.',
    answer: 'B',
    hint: '"no exceptions"라는 표현이 담고 있는 강도를 생각해보세요',
    explanation: 'A는 유연하고 여유로운 반응, B는 "예외 없다"는 명확한 단호함을 담고 있어요.',
  },
  {
    id: 'school_12',
    category: 'school',
    type: 'meaning',
    difficulty: 'easy',
    situation: '동기 학생이 과제에 대해',
    phrase: 'I\'m still trying to wrap my head around this.',
    choices: ['저는 아직 이걸 이해하려고 애쓰고 있어요', '저는 아직 이걸 머리에 두르고 있어요', '저는 아직 이걸 포장하고 있어요'],
    answer: 0,
    hint: '"wrap my head around"는 머리를 감싼다는 뜻이 아니에요',
    explanation: '"wrap one\'s head around something"은 어떤 개념을 이해하려고 애쓴다는 관용 표현이에요.',
  },
  {
    id: 'school_13',
    category: 'school',
    type: 'meaning',
    difficulty: 'medium',
    situation: '교수님이 그룹 프로젝트에 대해',
    phrase: 'I\'ll leave it up to you guys how you want to divide the work.',
    choices: ['업무를 어떻게 나눌지는 여러분이 알아서 정하세요', '업무는 제가 나눠서 여러분에게 남겨둘게요', '업무 분담은 여러분이 저에게 맡기세요'],
    answer: 0,
    hint: '"leave it up to you"는 결정권을 상대에게 준다는 뜻이에요',
    explanation: '업무 분담 방식을 학생들 재량에 맡기겠다는 뜻이에요.',
  },
  {
    id: 'school_14',
    category: 'school',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '교수님께 과제 연장을 조심스럽게 요청할 때',
    phrase: 'I know this is last minute, but ___ there any way I could get an extension?',
    choices: ['is', 'are', 'was'],
    answer: 0,
    hint: '"there is/are"의 의문문 도치 구조예요, "way"가 단수예요',
    explanation: '주어인 "way"가 단수라 "is"가 문법적으로 맞아요.',
  },
  {
    id: 'school_15',
    category: 'school',
    type: 'tone',
    difficulty: 'medium',
    situation: '조교 둘이 같은 채점 기준에 대해 두 가지로 설명했어요. 어느 쪽이 더 융통성 없게 들릴까요?',
    phraseA: 'We\'ll try to be flexible depending on the situation.',
    phraseB: 'The rubric is the rubric, we have to follow it exactly.',
    answer: 'B',
    hint: '"the rubric is the rubric"이라는 반복 표현이 주는 단호함을 느껴보세요',
    explanation: 'A는 상황에 따라 유연하게 대응하겠다는 태도, B는 규정을 정확히 따라야 한다는 단호함이에요.',
  },
  {
    id: 'school_16',
    category: 'school',
    type: 'response',
    difficulty: 'medium',
    situation: '교수님이 "I know finals are stressful, let me know if you need anything."라고 했어요. 가장 적절한 반응은?',
    choices: ['"Thanks, I really appreciate that."', '"Yes, I need something, thank you."', '"Thank you for your concern about my stress."'],
    answer: 0,
    hint: '배려의 말엔 짧고 진심 어린 감사로 답하는 게 자연스러워요',
    explanation: '"I really appreciate that"이 배려에 대한 가장 자연스러운 감사 표현이에요.',
  },
  {
    id: 'school_17',
    category: 'school',
    type: 'meaning',
    difficulty: 'medium',
    situation: '교수님이 시험 결과에 대해',
    phrase: 'The class as a whole didn\'t do as well as I\'d hoped.',
    choices: ['전체적으로 반이 제 기대만큼 잘하지 못했어요', '반 전체가 제가 바란 것보다 훨씬 잘했어요', '반의 절반은 제 기대만큼 했어요'],
    answer: 0,
    hint: '"as a whole"은 "전체적으로"라는 뜻이에요',
    explanation: '학급 전체 평균이 교수의 기대에 못 미쳤다는 뜻이에요.',
  },
  {
    id: 'school_18',
    category: 'school',
    type: 'tone',
    difficulty: 'medium',
    situation: '교수님이 학생의 질문에 대해 두 가지로 반응했어요. 어느 쪽이 더 귀찮아하는 느낌일까요?',
    phraseA: 'Great question, I\'m glad you asked.',
    phraseB: 'I think we covered that already, but sure.',
    answer: 'B',
    hint: '"but sure"라는 마지못한 듯한 표현을 주목해보세요',
    explanation: 'A는 질문을 환영하는 긍정적 반응, B는 "이미 다뤘는데"라며 은근히 귀찮음을 드러내는 뉘앙스예요.',
  },
  {
    id: 'school_19',
    category: 'school',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '발표 준비가 덜 됐다고 조심스럽게 말할 때',
    phrase: 'I\'m not ___ sure I\'m fully prepared for this, but I\'ll do my best.',
    choices: ['entirely', 'completely', 'totally'],
    answer: 0,
    hint: '"완전히 확신하지는 못한다"는 뜻을 자연스럽게 완화하는 부사를 골라보세요',
    explanation: '"not entirely sure"는 자기 확신 부족을 부드럽게 표현하는 가장 자연스러운 조합이에요.',
  },
  {
    id: 'school_20',
    category: 'school',
    type: 'meaning',
    difficulty: 'hard',
    situation: '교수님이 학생 논문에 대해',
    phrase: 'This is on the right track, but it needs more meat.',
    choices: ['이건 방향은 맞는데 고기가 더 필요해요', '이건 방향은 맞는데 내용이 더 필요해요', '이건 방향이 틀려서 다시 써야 해요'],
    answer: 1,
    hint: '"meat"가 여기서 식재료를 뜻하진 않아요',
    explanation: '"needs more meat"는 "내용/근거가 더 필요하다"는 뜻의 관용 표현이에요.',
  },
  {
    id: 'school_21',
    category: 'school',
    type: 'response',
    difficulty: 'medium',
    situation: '교수님이 "I don\'t usually do this, but I can give you a small extension."이라고 했어요. 가장 적절한 반응은?',
    choices: ['"Thank you so much, I really appreciate it."', '"Okay, thank you for the extension."', '"Great, so when\'s the new deadline?"'],
    answer: 0,
    hint: '예외적인 호의를 받았을 때는 감사를 충분히 표현하는 게 자연스러워요',
    explanation: '교수님이 "평소엔 안 하는데"라고 강조한 만큼, 진심 어린 감사 표현이 자연스러워요.',
  },
  {
    id: 'school_22',
    category: 'school',
    type: 'meaning',
    difficulty: 'hard',
    situation: '조교가 채점 기준에 대해',
    phrase: 'Don\'t read too much into the rubric, just do your best work.',
    choices: ['채점 기준을 너무 많이 읽지 마시고, 최선을 다하세요', '채점 기준을 너무 깊이 해석하지 마시고, 최선을 다하세요', '채점 기준을 다 읽으실 필요 없이, 대충 하세요'],
    answer: 1,
    hint: '"read into"는 "필요 이상으로 의미를 부여하다"는 뜻이에요',
    explanation: '"read too much into"는 과도하게 분석/해석하지 말라는 관용 표현이에요.',
  },
  {
    id: 'school_23',
    category: 'school',
    type: 'tone',
    difficulty: 'hard',
    situation: '교수님 둘이 같은 학생의 논문에 대해 두 가지로 평가했어요. 어느 쪽이 더 실망한 느낌일까요?',
    phraseA: 'There\'s definitely potential here, keep developing it.',
    phraseB: 'I expected a bit more depth, to be honest.',
    answer: 'B',
    hint: '"to be honest"라는 표현이 어떤 맥락에서 쓰이는지 생각해보세요',
    explanation: 'A는 가능성을 강조하는 격려의 태도, B는 "솔직히 말하면"으로 시작하며 기대에 못 미쳤음을 직접적으로 드러내요.',
  },
  {
    id: 'school_24',
    category: 'school',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '교수님께 이해 안 되는 부분을 조심스럽게 질문할 때',
    phrase: 'Sorry, could you go over that ___ time? I didn\'t quite catch it.',
    choices: ['one more', 'once more', 'one time'],
    answer: 0,
    hint: '"한 번 더"라는 뜻의 자연스러운 표현을 골라야 해요',
    explanation: '"one more time"이 가장 자연스럽고 흔한 표현이에요.',
  },
  {
    id: 'school_25',
    category: 'school',
    type: 'meaning',
    difficulty: 'hard',
    situation: '교수님이 과제 채점 후',
    phrase: 'You\'re not quite there yet, but you\'re getting closer.',
    choices: ['아직 거기 도착 못하셨지만, 가까워지고 있어요', '아직 완성도에는 못 미치지만, 점점 나아지고 있어요', '아직 거기 안 계시지만, 곧 오실 거예요'],
    answer: 1,
    hint: '"not quite there yet"은 물리적 장소가 아니라 목표 수준을 뜻해요',
    explanation: '"there"는 목표로 하는 완성도/수준을 비유적으로 가리켜요.',
  },
  {
    id: 'school_26',
    category: 'school',
    type: 'tone',
    difficulty: 'hard',
    situation: '조교 둘이 학생의 지각에 대해 두 가지로 반응했어요. 어느 쪽이 더 못마땅해하는 느낌일까요?',
    phraseA: 'No worries, these things happen.',
    phraseB: 'You made it, I see.',
    answer: 'B',
    hint: '"I see"라는 짧은 말이 어떤 감정을 담을 수 있는지 생각해보세요',
    explanation: 'A는 이해하고 넘어가는 태도, B는 "결국 오셨네요"라는 뉘앙스로 은근히 비꼬는 느낌이에요.',
  },
  {
    id: 'school_27',
    category: 'school',
    type: 'response',
    difficulty: 'hard',
    situation: '교수님이 성적에 대해 "I know this isn\'t the grade you wanted, but I stand by my evaluation."라고 했어요. 가장 적절한 반응은?',
    choices: ['"I understand, thank you for explaining your reasoning."', '"Can you just change it?"', '"That\'s not fair."'],
    answer: 0,
    hint: '교수님이 "제 평가를 고수한다"고 분명히 밝힌 입장을 존중하는 반응을 찾아보세요',
    explanation: '평가에 대한 이유를 이해하려는 태도로 받아들이는 게 가장 성숙하고 자연스러운 반응이에요.',
  },
  {
    id: 'school_28',
    category: 'school',
    type: 'fillBlank',
    difficulty: 'hard',
    situation: '교수님께 부담스러운 부탁(추천서)을 조심스럽게 할 때',
    phrase: 'I hate to ___ , but would you be willing to write me a recommendation letter?',
    choices: ['ask', 'bother', 'impose'],
    answer: 0,
    hint: '"부탁드리기 싫지만"이라는 뜻의 가장 흔하고 자연스러운 표현을 골라야 해요',
    explanation: '"I hate to ask"가 가장 흔하고 자연스러운 완곡 표현이에요.',
  },
  {
    id: 'school_29',
    category: 'school',
    type: 'tone',
    difficulty: 'hard',
    situation: '교수님 둘이 같은 학생의 수업 참여도에 대해 두 가지로 말했어요. 어느 쪽이 더 우회적으로 비판하는 느낌일까요?',
    phraseA: 'You should try to participate more in discussions.',
    phraseB: 'It\'d be great to hear your voice more in class.',
    answer: 'B',
    hint: '어느 쪽이 더 직접적인 지시고, 어느 쪽이 더 완곡하게 돌려 말하는지 보세요',
    explanation: 'A는 직접적인 개선 요청, B는 "목소리를 듣고 싶다"는 부드러운 표현으로 같은 지적을 우회적으로 전달해요.',
  },
  {
    id: 'school_30',
    category: 'school',
    type: 'fillBlank',
    difficulty: 'hard',
    situation: '교수님께 과제를 잘못 이해했을 수도 있다고 조심스럽게 인정할 때',
    phrase: 'I think I might ___ misunderstood the assignment instructions.',
    choices: ['have', 'has', 'had'],
    answer: 0,
    hint: '"might have p.p."는 과거 일에 대한 조심스러운 인정을 나타내요',
    explanation: '"might have misunderstood"는 "잘못 이해했을 수도 있다"는 뜻으로, 실수를 부드럽게 인정하는 표현이에요.',
  },
  {
    id: 'school_31',
    category: 'school',
    type: 'response',
    difficulty: 'hard',
    situation: '교수님이 논문 주제 변경에 대해 "I\'m a little hesitant about this new direction, but I\'m open to hearing your reasoning."라고 했어요. 가장 적절한 반응은?',
    choices: ['"That makes sense, let me explain why I think this could work."', '"So it\'s approved then?"', '"Why are you hesitant? It\'s a good idea."'],
    answer: 0,
    hint: '교수님이 "망설여지지만 들어볼 의향은 있다"고 한 뉘앙스를 정확히 읽는 반응을 찾아보세요',
    explanation: '교수의 조심스러운 태도를 이해하고, 논리적으로 설득할 준비를 하는 반응이 가장 자연스러워요.',
  },
  {
    id: 'school_32',
    category: 'school',
    type: 'meaning',
    difficulty: 'hard',
    situation: '동기 학생이 시험 준비에 대해',
    phrase: 'I\'m just trying to cram everything in before tomorrow.',
    choices: ['저는 그냥 내일 전까지 모든 걸 우겨넣으려고 해요', '저는 그냥 내일 전까지 벼락치기로 다 공부하려고 해요', '저는 그냥 내일 전까지 방을 정리하려고 해요'],
    answer: 1,
    hint: '"cram"은 좁은 공간에 억지로 넣는다는 뜻에서 왔지만, 여기선 특정 학습 방식을 가리켜요',
    explanation: '"cram"은 시험 직전에 벼락치기로 몰아서 공부한다는 뜻의 관용 표현이에요.',
  },
  {
    id: 'rent_01',
    category: 'rent',
    type: 'meaning',
    difficulty: 'easy',
    situation: '집주인이 계약 관련',
    phrase: 'Rent is due on the 1st of every month.',
    choices: ['월세는 매달 1일까지예요', '월세는 매달 1번만 내요', '월세는 첫 달에만 내요'],
    answer: 0,
    hint: '"due on"은 마감일을 뜻해요',
    explanation: '매달 1일이 월세 납부 기한이라는 뜻이에요.',
  },
  {
    id: 'rent_02',
    category: 'rent',
    type: 'meaning',
    difficulty: 'easy',
    situation: '이웃이 처음 인사하며',
    phrase: 'Just moved in?',
    choices: ['방금 이사 오셨어요?', '방금 나가셨어요?', '방금 이동하셨어요?'],
    answer: 0,
    hint: '"move in"은 새로 입주한다는 뜻이에요',
    explanation: '새로 이사 온 사람에게 하는 흔한 인사 질문이에요.',
  },
  {
    id: 'rent_03',
    category: 'rent',
    type: 'meaning',
    difficulty: 'medium',
    situation: '집주인이 수리 요청에 대해',
    phrase: 'I\'ll send someone over to take a look.',
    choices: ['제가 누군가를 보내서 살펴보게 할게요', '제가 누군가를 넘겨서 보여줄게요', '제가 직접 가서 봐드릴게요'],
    answer: 0,
    hint: '"send someone over"는 사람을 보낸다는 뜻이에요',
    explanation: '수리 기사를 보내서 문제를 확인하게 하겠다는 뜻이에요.',
  },
  {
    id: 'rent_04',
    category: 'rent',
    type: 'response',
    difficulty: 'easy',
    situation: '이웃이 "Do you need anything from the store? I\'m heading out."라고 물었어요. 필요한 게 없을 때 자연스러운 대답은?',
    choices: ['"No, I\'m good, thanks though!"', '"No, I don\'t need anything from there."', '"No, there is nothing I need."'],
    answer: 0,
    hint: '캐주얼하게 짧게 거절하면서 감사 표현도 곁들이면 좋아요',
    explanation: '"I\'m good, thanks though"는 호의를 거절하면서도 감사를 표현하는 자연스러운 표현이에요.',
  },
  {
    id: 'rent_05',
    category: 'rent',
    type: 'meaning',
    difficulty: 'easy',
    situation: '집주인이 계약서 관련',
    phrase: 'Just sign here and you\'re all set.',
    choices: ['여기 서명하시면 다 끝나요', '여기 서명하시면 다 준비된 거예요', '여기 서명은 나중에 준비되면 하세요'],
    answer: 0,
    hint: '"you\'re all set"은 다 완료됐다는 뜻이에요',
    explanation: '서명만 하면 절차가 모두 끝난다는 뜻이에요.',
  },
  {
    id: 'rent_06',
    category: 'rent',
    type: 'response',
    difficulty: 'easy',
    situation: '이웃이 "I made too much food, want some?"이라고 물었어요. 받고 싶을 때 자연스러운 대답은?',
    choices: ['"Sure, that\'d be great, thank you!"', '"Yes, I want some food."', '"I would like to accept your food."'],
    answer: 0,
    hint: '캐주얼한 호의엔 캐주얼하게 감사히 받는 반응이 자연스러워요',
    explanation: '"that\'d be great, thank you"가 호의를 자연스럽게 수락하는 흔한 표현이에요.',
  },
  {
    id: 'rent_07',
    category: 'rent',
    type: 'meaning',
    difficulty: 'medium',
    situation: '집주인이 계약 갱신에 대해',
    phrase: 'Let me know if you\'re thinking of renewing.',
    choices: ['갱신 생각 있으시면 알려주세요', '갱신은 생각하지 마시고 알려주세요', '갱신하실 거면 다시 생각해보세요'],
    answer: 0,
    hint: '"let me know if"는 "~라면 알려달라"는 뜻이에요',
    explanation: '재계약 의사가 있으면 미리 알려달라는 요청이에요.',
  },
  {
    id: 'rent_08',
    category: 'rent',
    type: 'fillBlank',
    difficulty: 'easy',
    situation: '이웃에게 소음에 대해 물어볼 때',
    phrase: 'Is it okay if I ask about the noise ___ night?',
    choices: ['at', 'in', 'on'],
    answer: 0,
    hint: '"at night"는 "밤에"라는 뜻의 고정 표현이에요',
    explanation: '"at night"은 시간대를 나타내는 관용적 전치사 조합이에요.',
  },
  {
    id: 'rent_09',
    category: 'rent',
    type: 'meaning',
    difficulty: 'medium',
    situation: '집주인이 보증금에 대해',
    phrase: 'You\'ll get your deposit back, minus any damages.',
    choices: ['손상된 부분을 뺀 보증금을 돌려받으실 거예요', '손상이 없으면 보증금을 못 받으실 거예요', '보증금은 손상 여부와 상관없이 다 돌려받으세요'],
    answer: 0,
    hint: '"minus"는 "~를 뺀"이라는 뜻이에요',
    explanation: '파손된 부분에 대한 비용을 제외하고 나머지 보증금을 돌려받는다는 뜻이에요.',
  },
  {
    id: 'rent_10',
    category: 'rent',
    type: 'response',
    difficulty: 'medium',
    situation: '이웃이 "I noticed your package got left outside for a while, hope it was okay."라고 했어요. 가장 적절한 반응은?',
    choices: ['"Oh, thanks for keeping an eye out!"', '"Why didn\'t you bring it inside for me?"', '"It\'s fine, I don\'t care about packages."'],
    answer: 0,
    hint: '이웃이 지나가며 관심을 보여준 것에 대해 어떻게 반응하는 게 자연스러운지 생각해보세요',
    explanation: '이웃이 신경 써준 것에 대해 가볍게 감사를 표하는 게 자연스러워요.',
  },
  {
    id: 'rent_11',
    category: 'rent',
    type: 'tone',
    difficulty: 'easy',
    situation: '집주인이 수리 요청에 대해 두 가지로 답했어요. 어느 쪽이 더 귀찮아하는 느낌일까요?',
    phraseA: 'Of course, I\'ll get that taken care of soon.',
    phraseB: 'Again? Okay, I\'ll look into it.',
    answer: 'B',
    hint: '"again?"이라는 반문이 담고 있는 감정을 생각해보세요',
    explanation: 'A는 흔쾌히 수락하는 태도, B는 "또요?"라며 은근히 짜증을 드러내는 뉘앙스예요.',
  },
  {
    id: 'rent_12',
    category: 'rent',
    type: 'meaning',
    difficulty: 'easy',
    situation: '이웃이 파티 소음에 대해 미리',
    phrase: 'Just a heads up, we\'re having people over Saturday.',
    choices: ['미리 알려드리는데, 토요일에 손님들이 와요', '머리 조심하세요, 토요일에 사람들이 와요', '토요일에 사람들 머리를 세러 와요'],
    answer: 0,
    hint: '"heads up"은 미리 알려주는 정보라는 뜻의 관용 표현이에요',
    explanation: '"a heads up"은 사전 안내/경고를 뜻하는 캐주얼한 표현이에요.',
  },
  {
    id: 'rent_13',
    category: 'rent',
    type: 'meaning',
    difficulty: 'medium',
    situation: '집주인이 계약 조건에 대해',
    phrase: 'That\'s pretty standard, most leases have that clause.',
    choices: ['그건 꽤 표준적이에요, 대부분 계약서에 그 조항이 있어요', '그건 꽤 이상해요, 대부분 계약서엔 그 조항이 없어요', '그건 서 있어야 하는 조항이에요'],
    answer: 0,
    hint: '"standard"는 "표준적인, 흔한"이라는 뜻이에요',
    explanation: '특별한 조항이 아니라 대부분의 임대 계약에 흔히 있는 조건이라는 뜻이에요.',
  },
  {
    id: 'rent_14',
    category: 'rent',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '이웃에게 조심스럽게 소음 문제를 얘기할 때',
    phrase: 'I hope this isn\'t awkward, but ___ you mind keeping it down a bit after 10?',
    choices: ['would', 'do', 'could'],
    answer: 0,
    hint: '아주 정중한 부탁을 할 때 쓰는 조동사예요',
    explanation: '"would you mind ~ing?"는 아주 정중하게 부탁할 때 쓰는 표준 구조예요.',
  },
  {
    id: 'rent_15',
    category: 'rent',
    type: 'tone',
    difficulty: 'medium',
    situation: '집주인 둘이 세입자의 요청에 대해 두 가지로 반응했어요. 어느 쪽이 더 마지못해 승낙하는 느낌일까요?',
    phraseA: 'Sure, that should be fine!',
    phraseB: 'I guess that should be fine.',
    answer: 'B',
    hint: '"I guess"라는 표현이 담고 있는 망설임을 생각해보세요',
    explanation: 'A는 흔쾌한 승낙, B는 "I guess"로 시작하며 내키지 않지만 어쩔 수 없이 받아들이는 뉘앙스예요.',
  },
  {
    id: 'rent_16',
    category: 'rent',
    type: 'response',
    difficulty: 'medium',
    situation: '이웃이 "Sorry if my dog barked too much last night, he gets anxious sometimes."라고 했어요. 가장 적절한 반응은?',
    choices: ['"No worries at all, I totally get it."', '"It\'s okay, I understand your dog\'s anxiety."', '"Don\'t worry, dogs bark sometimes."'],
    answer: 0,
    hint: '진심 어린 사과엔 편하게 이해한다는 반응이 자연스러워요',
    explanation: '"I totally get it"은 상대의 사정을 이해한다는 뜻의 자연스러운 캐주얼 표현이에요.',
  },
  {
    id: 'rent_17',
    category: 'rent',
    type: 'meaning',
    difficulty: 'medium',
    situation: '집주인이 수리 일정에 대해',
    phrase: 'I\'ll swing by sometime this week to fix it.',
    choices: ['이번 주 중에 잠깐 들러서 고쳐드릴게요', '이번 주에 그네를 타고 지나갈게요', '이번 주는 고치기 힘들 것 같아요'],
    answer: 0,
    hint: '"swing by"는 짧게 들른다는 뜻의 관용 표현이에요',
    explanation: '이번 주 중 편한 시간에 방문해서 수리하겠다는 뜻이에요.',
  },
  {
    id: 'rent_18',
    category: 'rent',
    type: 'tone',
    difficulty: 'medium',
    situation: '이웃 둘이 서로의 반려견 문제에 대해 두 가지로 말했어요. 어느 쪽이 더 참다가 터진 느낌일까요?',
    phraseA: 'Hey, just wanted to mention, your dog\'s been barking a bit at night.',
    phraseB: 'Okay, this has been going on for weeks now, we really need to talk about your dog.',
    answer: 'B',
    hint: '"몇 주째"라는 표현과 "정말 얘기해야 한다"는 강조가 담긴 감정을 생각해보세요',
    explanation: 'A는 가볍게 처음 언급하는 느낌, B는 "몇 주째"를 강조하며 참았던 불만이 터진 뉘앙스예요.',
  },
  {
    id: 'rent_19',
    category: 'rent',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '집주인에게 이사 나가는 날짜를 미리 알릴 때',
    phrase: 'I just wanted to give you a heads ___ that I\'ll be moving out next month.',
    choices: ['up', 'on', 'for'],
    answer: 0,
    hint: '"미리 알려주다"라는 뜻의 고정 표현이에요',
    explanation: '"give someone a heads up"은 사전에 미리 알려준다는 뜻의 관용 표현이에요.',
  },
  {
    id: 'rent_20',
    category: 'rent',
    type: 'meaning',
    difficulty: 'hard',
    situation: '집주인이 세입자의 요청에 대해',
    phrase: 'Let me see what I can do, but no promises.',
    choices: ['제가 뭘 할 수 있는지 볼게요, 근데 약속은 못 해요', '제가 할 수 있는 건 다 할 테니, 약속을 지킬게요', '제가 볼 수 있는 건 없으니 약속하지 마세요'],
    answer: 0,
    hint: '"no promises"는 확답을 피하는 표현이에요',
    explanation: '노력은 해보겠지만 확실히 될 거라고 장담은 못 한다는 신중한 표현이에요.',
  },
  {
    id: 'rent_21',
    category: 'rent',
    type: 'response',
    difficulty: 'medium',
    situation: '이웃이 "I know it\'s a lot to ask, but could you water my plants while I\'m away?"라고 물었어요. 가능할 때 자연스러운 대답은?',
    choices: ['"Of course, happy to help!"', '"Yes, I am willing to do that."', '"It\'s not too much to ask, I\'ll do it."'],
    answer: 0,
    hint: '캐주얼한 부탁엔 캐주얼하고 흔쾌한 반응이 자연스러워요',
    explanation: '"happy to help"는 부탁을 흔쾌히 수락하는 자연스러운 캐주얼 표현이에요.',
  },
  {
    id: 'rent_22',
    category: 'rent',
    type: 'meaning',
    difficulty: 'hard',
    situation: '집주인이 수리비에 대해',
    phrase: 'That\'s on us, don\'t worry about it.',
    choices: ['그건 우리 위에 있으니 걱정 마세요', '그건 저희가 부담할게요, 걱정 마세요', '그건 걱정할 필요 없이 저희가 나중에 알려드릴게요'],
    answer: 1,
    hint: '"that\'s on us"는 물리적 위치가 아니라 책임/비용에 대한 표현이에요',
    explanation: '"that\'s on us"는 "우리가 그 비용/책임을 지겠다"는 뜻의 관용 표현이에요.',
  },
  {
    id: 'rent_23',
    category: 'rent',
    type: 'tone',
    difficulty: 'hard',
    situation: '집주인 둘이 세입자의 계약 연장 요청에 대해 두 가지로 답했어요. 어느 쪽이 더 실질적으로 거절에 가까울까요?',
    phraseA: 'Let\'s sit down and talk about the terms next week.',
    phraseB: 'We\'ll have to see how things look closer to the date.',
    answer: 'B',
    hint: '누가 구체적인 시점을 제시하고, 누가 막연하게 미루는지 보세요',
    explanation: 'A는 구체적인 시점(다음 주)을 제시하며 논의할 의지를 보임, B는 "날짜가 가까워지면"이라는 막연한 표현으로 확답을 피하며 사실상 미루는 뉘앙스예요.',
  },
  {
    id: 'rent_24',
    category: 'rent',
    type: 'fillBlank',
    difficulty: 'medium',
    situation: '이웃에게 소포를 대신 받아달라고 부탁할 때',
    phrase: 'Would you mind ___ my package if it comes while I\'m out?',
    choices: ['holding onto', 'hold onto', 'to hold onto'],
    answer: 0,
    hint: '"would you mind"는 뒤에 동명사가 와야 해요',
    explanation: '"would you mind + 동명사"가 문법적으로 맞는 구조예요.',
  },
  {
    id: 'rent_25',
    category: 'rent',
    type: 'meaning',
    difficulty: 'hard',
    situation: '집주인이 임대 계약 갱신에 대해',
    phrase: 'I don\'t want to jump to conclusions, but I noticed some wear and tear.',
    choices: ['결론으로 뛰어들고 싶지는 않지만, 마모된 부분이 좀 보이네요', '성급히 판단하고 싶지는 않지만, 마모된 부분이 좀 보이네요', '빨리 결론을 내려야겠지만, 마모된 부분이 좀 보이네요'],
    answer: 1,
    hint: '"jump to conclusions"는 성급하게 결론짓는다는 관용 표현이에요',
    explanation: '"jump to conclusions"는 충분한 근거 없이 성급하게 판단한다는 관용 표현이에요.',
  },
  {
    id: 'rent_26',
    category: 'rent',
    type: 'tone',
    difficulty: 'hard',
    situation: '이웃 둘이 서로의 주차 문제에 대해 두 가지로 말했어요. 어느 쪽이 더 참을성이 바닥난 느낌일까요?',
    phraseA: 'Hey, just a friendly reminder that spot\'s technically mine.',
    phraseB: 'This is the third time this week — we need to sort this out.',
    answer: 'B',
    hint: '구체적인 횟수를 언급하며 "해결해야 한다"고 강조하는 게 어떤 감정을 담고 있는지 보세요',
    explanation: 'A는 부드럽고 가벼운 리마인더, B는 "이번 주에만 세 번째"를 강조하며 명백히 인내심이 다한 뉘앙스예요.',
  },
  {
    id: 'rent_27',
    category: 'rent',
    type: 'response',
    difficulty: 'hard',
    situation: '집주인이 수리 지연에 대해 "I wish I could get to this sooner, but I\'ve got a few other things going on."라고 했어요. 가장 적절한 반응은?',
    choices: ['"I understand, just let me know when you can."', '"But this is urgent for me."', '"How long is \'a few things\' going to take?"'],
    answer: 0,
    hint: '집주인이 미안해하며 사정을 설명한 것에 대해 이해를 표하면서도 필요한 걸 챙기는 반응을 찾아보세요',
    explanation: '상대의 사정을 인정하면서도 자신의 필요를 부드럽게 전달하는 게 자연스러워요.',
  },
  {
    id: 'rent_28',
    category: 'rent',
    type: 'fillBlank',
    difficulty: 'hard',
    situation: '이웃에게 예민한 얘기(반려동물 냄새)를 조심스럽게 꺼낼 때',
    phrase: 'This is a little awkward, but I ___ mention that there\'s been a smell coming from the hallway.',
    choices: ['wanted to', 'want', 'wants to'],
    answer: 0,
    hint: '조심스러운 화제를 꺼낼 때는 과거형으로 완곡하게 표현하는 경우가 많아요',
    explanation: '"I wanted to mention"은 "I want to mention"보다 더 부드럽고 조심스럽게 들리는 완곡 표현이에요.',
  },
  {
    id: 'rent_29',
    category: 'rent',
    type: 'tone',
    difficulty: 'hard',
    situation: '집주인 둘이 세입자의 보증금 반환 문의에 대해 두 가지로 답했어요. 어느 쪽이 더 책임을 회피하는 느낌일까요?',
    phraseA: 'Let me check on that and get back to you by Friday.',
    phraseB: 'That\'s usually handled by the management company, not me.',
    answer: 'B',
    hint: '누가 직접 확인하겠다고 하고, 누가 다른 곳으로 넘기는지 보세요',
    explanation: 'A는 직접 확인해서 답을 주겠다는 책임감 있는 태도, B는 "그건 관리회사 소관"이라며 책임을 다른 곳으로 넘기는 뉘앙스예요.',
  },
  {
    id: 'rent_30',
    category: 'rent',
    type: 'fillBlank',
    difficulty: 'hard',
    situation: '집주인에게 수리 요청을 깜빡 안 했다고 조심스럽게 인정할 때',
    phrase: 'I think I might ___ forgotten to send that maintenance request.',
    choices: ['have', 'has', 'had'],
    answer: 0,
    hint: '"might have p.p."는 조심스러운 인정/추측을 나타내는 구조예요',
    explanation: '"might have forgotten"은 "깜빡했을 수도 있다"는 뜻으로, 실수를 부드럽게 인정하는 표현이에요.',
  },
  {
    id: 'rent_31',
    category: 'rent',
    type: 'response',
    difficulty: 'hard',
    situation: '이웃이 공용 공간 사용 규칙에 대해 "I don\'t want to sound like the rule police, but we do need to keep the hallway clear."라고 했어요. 가장 적절한 반응은?',
    choices: ['"No, that\'s totally fair, I\'ll move my stuff."', '"I didn\'t know there was a rule police."', '"It\'s just my stuff, it\'s not a big deal."'],
    answer: 0,
    hint: '"rule police처럼 들리고 싶지 않다"는 표현이 상대가 조심스럽게 지적하고 있다는 신호라는 걸 이해하는 반응을 찾아보세요',
    explanation: '상대가 조심스럽게 돌려 말한 지적을 순순히 받아들이는 게 성숙하고 자연스러운 반응이에요.',
  },
  {
    id: 'rent_32',
    category: 'rent',
    type: 'meaning',
    difficulty: 'hard',
    situation: '집주인이 세입자와의 갈등에 대해',
    phrase: 'I don\'t want this to turn into a bigger issue than it needs to be.',
    choices: ['이게 필요 이상으로 더 큰 문제로 바뀌지 않았으면 해요', '이게 원래 큰 문제로 바뀌어야 한다고 생각해요', '이 문제가 다른 문제로 변해야 해요'],
    answer: 0,
    hint: '"turn into"는 상태가 변한다는 뜻이고, "than it needs to be"가 핵심이에요',
    explanation: '지금 사안이 불필요하게 확대되지 않기를 바란다는 뜻으로, 갈등을 최소화하고 싶어하는 태도예요.',
  },
]
